### ISSUE TITLE
HTTP 403 Forbidden from ADFS

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#1000]
**What Happened**
From @mkewins , @jwrcoleman :

> https://move.intra.prod-toronto.ca/api/auth/adfs-init returns:
> `{"statusCode":403,"error":"Forbidden","message":"Forbidden"}`

This occurred when logging into MOVE via ADFS on June 30, 2021.  When this happens, the user can full-refresh to restore functionality.

**What Should Happen**
The user should be able to log in.

**To Reproduce**
This only happens occasionally; we have a couple of theories as to what's happening (see Additional Notes), but no reliable repro.

**Additional Notes**
We have two working theories:

1. this is caused by updates / maintenance to ADFS;
2. this is caused by some cookie or cached token in MOVE (either client-side or server-side) plus ADFS token expiry.

@candu had a longer explanation of 2):

> ...or maybe this has to do with expiry of some ADFS-related token/cookie?  not 100% sure how long those are good for, but it's possible that this could result from:
> - user signs in to ADFS, which results in a token T;
> - some time later, T expires;
> - some time after that, user signs in to ADFS, which uses T again, which fails.
> 
> in which case we'd need to figure out how long T is good for, and then figure out how to not keep using T after it expires.  (I'd have to dig back into the internals of MOVE auth, and also inspect the OAuth2 flow a bit, to see if this is right / plausible.  Part of the difficulty is testing with an expired token, which means waiting for a token to expire if you're not in control of the OAuth2 server yourself :hourglass_flowing_sand:)

For this outage we contacted Directory Services, who were unaware of any updates / maintenance to ADFS around this time - which is some evidence against 1).

**Comment by mkewins** [comment]
A user reported that this also happens when clicking on the links from our emails (into study requests).

Donna also reported that this happens when clicking the "Sign In" button the bottom-left of the sidebar (the little door with the arrow pointing inwards).

I've increased the priority to `p1` in response to these issues.

**Comment by mkewins** [comment]
This still happens for me when clicking any direct link to a page sitting behind the login / auth.

**Comment by mkewins** [comment]
I can't reproduce this bug anymore, going to close.
