### ISSUE TITLE
Investigate differences between FLOW and MOVE for Bay / Davenport

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#1015]
**What Happened**
There are inconsistencies in the TMC Summary Report for Bay / Davenport, between the FLOW and MOVE reports for the same date.

**What Should Happen**
The values in MOVE should be correct. _Not necessarily_ equal to those in FLOW, but correct according to the definitions of peak hour, and summation of the raw data, and there should not be a row of all zeroes.

**To Reproduce**
Steps to reproduce the bug:
1. Go to [Bay / Davenport](https://move.intra.prod-toronto.ca/view/location/s1:AwttmB/POINTS)
2. Click on 'View Reports' for TMCs
3. View the 'TMC Summary Report' for March 24, 2018

Three issues:
- The `AM PEAK`, `PM PEAK`, `2 HOUR AM`, and `2 HOUR PM` time buckets differ from those of FLOW
- The `OFF HOUR AVG` is all zeroes
- The `TOTAL SUM` volume of MOVE (12,342) != FLOW (12,513) (_even though_ the values in the table itself are the same...)

**Screenshots**
MOVE - TMC Summary Report
[COUNT_SUMMARY_TURNING_MOVEMENT_DAVENPORT_RD_BAY_ST_2018-03-24_5_36889.pdf](https://github.com/CityofToronto/bdit_flashcrow/files/6824763/COUNT_SUMMARY_TURNING_MOVEMENT_DAVENPORT_RD_BAY_ST_2018-03-24_5_36889.pdf)

FLOW - TMC Summary Report
[Bay&Davenport_2018_Sat.pdf](https://github.com/CityofToronto/bdit_flashcrow/files/6824767/Bay.Davenport_2018_Sat.pdf)

**Additional Notes**
I have a hunch that the first issue is due to a difference in how we calculate the peak hours in MOVE vs. FLOW.

- MOVE `AM PEAK` = highest sum of vehicle volume in any 1-hour range between 00:00-12:00
- MOVE `PM PEAK` = highest sum of vehicle volume in any 1-hour range between 12:00-24:00
- Same goes for the 2-hour peaks, except for

**Comment by candu** [comment]
Here's a [link to the live report in MOVE](https://move.intra.prod-toronto.ca/view/location/s1:AwttmB/POINTS/reports/TMC).

## Totals

I notice that 12,342 _does_ show up on the FLOW report, at bottom-left - this is the 8-hour vehicle total.  From there, we have 12,342 + 171 = 12,513 - so this total is vehicles + bicycles (without pedestrians, other).

In MOVE, we also have the total 13,531 at left in the section.  This comes from 12,342 + 1,018 + 171 + 0 = 13,531 - it includes _all_ modes (i.e. vehicles + pedestrians + bicycles + other).

## Peak Hours

First: off peak hours.  As noted by @mkewins , MOVE uses the highest 1-hour / 2-hour totals from 00:00-12:00 (AM) and 12:00-24:00 (PM).  Off-peak hours, then, are all hours from the end of the AM 2-hour peak to the start of the PM 2-hour peak...

...which, in this case, is 12:00-13:00 - but we have no data for that time period, so it shows up as zero!

One longstanding task on our plate is to clarify what _exactly_ peak hours vs. off-peak hours mean: do we include all possible AM / PM hours when calculating the peak?  Or should we only consider certain AM / PM hours?  And what happens on weekends (e.g. this count), where weekday rush hours don't matter as much?  Should off-peak hours just be the hours between the AM and PM peaks, or should they be _all_ other hours during the TMC?  Should we include pedestrians and other modes when computing peaks, or not?  (It's clear that FLOW didn't do this; does Vision Zero 2.0 change that decision at all?)

There are a lot of questions here that need clear explanations / decisions - and this feels especially important now that we're starting to think beyond just "let's do what FLOW did".

**Comment by candu** [comment]
(As a side note, this could be a good opportunity to introduce @leonL - and our incoming data engineer! - to divisional stakeholders who make decisions like this.)

**Comment by leonL** [comment]
The Data team has decided that the MOVE should calculate TMC summaries according to updated definitions instead of mirroring the logic used in Flow.
