### ISSUE TITLE
Request Study: move "Use map..." card below list of requests

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#1019]
**Description**
In Request Study, we currently show a "Use map..." prompt above the list of requests.  This task moves that below the list of requests.

**Acceptance Criteria**
- [ ] the "Use map..." card has been moved below the list of requests, and above "Request Priority and Details".

**Additional Notes**
This is based off usability feedback from users: when they add new locations, they're at the bottom of the list, and some users have reported scrolling all the way to the top to access this card.  (As a side note: all that the "Search Map" button does is focus the search bar on the map; however, this alternate interaction is not easily discoverable.)

See `<FcDrawerRequestStudyNew>` for card markup.

**Comment by mkewins** [comment]
This is not aligned with current priorities (focus on collision data parity with legacy systems). We may revisit this in the future.
