### ISSUE TITLE
Request Study: numbers truncated in icons when requesting 10 or more studies

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#1024]
**What Happened**
In Request Study, when a user requests 10 or more studies, it only shows the first digit of "10", "11", etc. in the map pin icon.

**What Should Happen**
The whole number should be visible in the map pin icon.

**To Reproduce**
Steps to reproduce the bug:
1. Log into MOVE
2. Go to any location
3. Click "Request New"
4. Add a study request using the map
5. Repeat 4. until there are 10 or more studies being requested

**Screenshots**
Map pin icons: "9" is followed by "1".

![number truncation in map pin icon: "10" reads as "1"](https://user-images.githubusercontent.com/151605/125859963-a9adf045-4658-4b3a-b45a-6e6562d0087e.png)

**Additional Notes**
The icon is rendered by `<FcIconLocationMulti>`, using the `locationIndex` prop.

**Comment by mkewins** [comment]
Migrated to Jira.
