### ISSUE TITLE
Request Study: multiple pins on map at same location become garbled

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#1025]
**What Happened**
In Request Study, when the user requests multiple studies at the same location, it tries to render multiple map pins at that location.  This results in garbled and unreadable numbers in the pins on the map.

**What Should Happen**
Numbers should not become garbled.  See Additional Notes for thoughts here.

**To Reproduce**
Steps to reproduce the bug:
1. Log into MOVE
2. Go to any location
3. Click "Request New"
4. Use the map to add multiple studies at the same location

**Screenshots**
For frontend bugs, provide a browser screenshot if possible.  For backend bugs, screenshots of either the frontend dev tools (e.g. Network tab showing API responses or errors, Console tab showing errors) or the backend `node --inspect` dev tools (e.g. Debugger tab showing the issue) are helpful.

**Additional Notes**
This is somewhat related to #1024 , in that both that issue and this issue deal with the presentation of pins in Request Study.  MapLibre GL JS pins are managed in `lib/geo/GeoStyle`; you will likely need to become familiar with [MapLibre GL JS styles](https://maplibre.org/maplibre-gl-js-docs/style-spec/) to make progress here.

There are several possible approaches to fixing this:

1. show a single pin with a range or series of numbers (e.g. "1-5");
2. show a single pin with the highest number at that location (e.g. "5" if requests 1-5 are there);
3. spread pins out a bit to make them all visible.

Approach 1 has the advantage of showing all the info, but it may be difficult to fit this text on a pin without making the text unreadably small.

Approach 2 is easiest of the three, but it makes it difficult to tell which studies are being requested at that location, and might lead to confusion about missing studies.

Approach 3 is more difficult, but would also arguably be the most readable.  It also sidesteps the limitations here on text length.

**Comment by mkewins** [comment]
Migrated to Jira.
