### ISSUE TITLE
Infra: procure and setup on-prem server, move replicator there

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#1028]
**Description**
In the [MOVE Physical Component Diagram](https://www.notion.so/bditto/MOVE-Physical-Component-Diagram-2a35b14ae84c4f15b8758dad19dfb81a), we have an on-prem component called `replicator`.

`replicator` currently runs on a City workstation that sits on @candu 's old desk.  This task aims to replace that workstation with a properly-managed dedicated on-prem server in City datacenters, and to move `replicator` into that on-prem server.  This should improve the reliability of `replicator` and make it easier to maintain.

**Acceptance Criteria**
- [x] communicate on-prem server needs to Tech Services;
- [ ] procure on-prem server (see Additional Notes for requirements);
- [ ] ensure requirements below are met;
- [ ] migrate `replicator` to on-prem server:
  - [ ] port existing replication scripts over to Airflow;
  - [ ] ensure DAG failure notifications are being sent from that machine to `move-ops`;
  - [ ] stop `replicator` on ad-hoc workstation;
  - [ ] test new `replicator` out in Airflow;
  - [ ] once working, clean up `replicator`.

**Additional Notes**
This work can be done within the `bdit_move_scripts` repo (@candu to set up access there).

This is _not_ a good first task for new hires!  There will be upfront time to discuss needs with Tech Services and procure the server.  These requests / conversations may require a lot of follow-up and/or need to be escalated.  (So: not a good "I want to understand things and dive in" task, but maybe a _very good_ "I've done some things and met some people and want to do something awesome for the longer-term health of MOVE" task!)

In a thread with Tech Services, we previously communicated these needs:

- an on-prem Linux-based VM…
  - that can access…
    - the network drive (specifically \\trafic\documents);
    - the Oracle database at mcgill.corp.toronto.ca (specifically the TRAFFIC user on the FLOW service);
    - the corresponding MOVE ETL environment (to scp files to it);
  - that has installed…
    - PostgreSQL 11 or later;
    - Airflow 2
    - Python 3 (we're using Python 3.7.2 elsewhere, but latest 3.x is fine);
    - nginx;
  - that has configuration…
    - similar to cot-env.config on our ETL AWS environments;
    - similar to .pgpass on our ETL AWS environments;
    - probably something similar to tnsnames.ora is needed to access the Oracle database?
  - that we can:
    - SSH into;
    - sudo on;
    - send email to move-ops@toronto.ca from (for monitoring / alerting around data pipelines).

As a first step here, that thread should be picked up again; @candu to do handoff with new dev here if possible.

More background on `replicator`: this component of MOVE regularly dumps data from the legacy Oracle database that backs CRASH and FLOW, and then copies that data to our `etl` servers.  After the data arrives in `etl`, it is later loaded into the MOVE database by the `replicator_transfer_crash` and `replicator_transfer_flow` DAGs in Airflow.  (See the [Airflow dashboard (internal-only)](https://flashcrow-etladmin.intra.dev-toronto.ca/airflow/admin/) for more details there.)

**Comment by candu** [comment]
Meeting scheduled for next week to move this forward (thanks @jwrcoleman !)

Based on the specs from previous emails, it looks like Medium would work well - this should meet our needs for the next while.  (Also curious what the upgrade process looks like, if we later start to exceed capacity.)

**Comment by mkewins** [comment]
This is in progress, and work is being tracked in Jira.
