### ISSUE TITLE
ETL: investigate additional tools for validation, Airflow DAG management

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#1029]
**Description**
At time of writing, we have 18 DAGs in Airflow, managing everything from periodic `VACUUM ANALYZE` runs to centreline conflation to fetching Open Data datasets and GIS layers.

This task aims to investigate additional tools like `dbt`, Great Expectations, `SensorOperator`, etc. to improve the state of validation and management.  For more details, see Additional Notes.

As we plan for adding data loading functionality to move, and for gradual replacement of / improvement over FlowLoad, having better tools in place to manage the growing complexity of these pipelines will be extremely helpful.  (In other words: this aims to pay down technical debt that we've deliberately taken on to get MOVE to where it is now.)

**Acceptance Criteria**
This task is more oriented towards technical research.

- [ ] document process and findings in a new subpage of [Technical Research (internal-only)](https://www.notion.so/bditto/Technical-Research-b90dd84440d840ec89e6f313fa60bd3f);
- [ ] ask around Data + Analytics for their thoughts on best practices;
- [ ] evaluate tools for improving validation / management, possibly including:
  - [ ] `dbt`;
  - [ ] Great Expectations;
  - [ ] Airflow sensor operators;
  - [ ] Airflow task SLAs;
  - [ ] `pdoc3` for Python documentation.

If you find tools that help, create additional issues to track adoption / implementation as needed.  Aside from that, whoever's assigned to this task is also responsible for deciding when it can be closed.

**Additional Notes**
One promising approach is detailed in [this article](https://opendatascience.com/building-a-robust-data-pipeline-with-the-dag-stack-dbt-airflow-and-great-expectations/).  In that approach, [`dbt`](https://docs.getdbt.com/) is used to provide more structure to declared views / tables, while [Great Expectations](https://greatexpectations.io/) is used to help validate loaded data.

> We don't necessarily need all pieces of that approach; part of this task is to look into these tools, and to pick tools that will help make MOVE's data pipelines more maintainable and reliable.

Until now, we've been able to get by on a mix of ad-hoc scripts, carefully chosen `cron`-like schedules, and little to no validation.  

Ad-hoc scripts: all of our pipelines are built up out of bash, Python, and SQL scripts.  We have relatively little documentation within scripts, no documentation of how these scripts and pipelines fit together, and no way to know whether a change in one script will break pipelines elsewhere (well, aside from the baseline "try it and see" strategy).  We could use better documentation here - ideally, that documentation would be generated from the codebase, to reduce the rate at which it drifts from reality.  It's also possible that tools like `dbt` might help provide better guarantees around changes to these pipelines over time.

As an example of scheduling: `arteries_geocoding`, `group_multidirection_arteries`, and `group_multiday_counts` are intended to run in that order, but we don't actually ensure that they do.  Instead, we've just spaced their schedules out by 30 minutes.  This might be a good place to use [sensor operators](https://marclamberti.com/blog/airflow-sensors/), [task SLAs](https://airflow.apache.org/docs/apache-airflow/stable/concepts/tasks.html#slas), or other similar tools.

Another example: `replicator_transfer_crash` and `replicator_transfer_flow` are designed to run after MOVE's on-prem `replicator` component (see #1028 for upcoming infra changes there!) copies data to `etl`.  Again, we don't ensure this; we just leave what we hope is enough time for `replicator` to run before starting these DAGs.  Here sensor operators might be able to detect that the data files have been updated, and only start loading data in `etl` once that happens.

Validation: aside from some basic checksum and `COUNT(*)` checks in our `replicator` pipelines, we don't have any automated validation of our data pipelines.  Even if we only had _very basic_ validation, that would still be an improvement!  Here a tool like Great Expectations could help us add validation into our data pipelines, giving us more confidence that they are functioning as expected.

**Comment by mkewins** [comment]
@peter-lyons has been exploring Spark and a new replicator setup as an improvement to Airflow and ETL management, which comes with opportunities to introduce data validation and quality benchmarks, as well as improve scheduling dependencies. More information is available in [Notion (internal link only)](https://www.notion.so/bditto/Move-Data-Platform-6ae885e9e715431b9d8bebd305e28f0e).
