### ISSUE TITLE
Speed / Volume ATR study data expected but not available at Shoreham Drive: Gosford Blvd - Hullmar Park Trail

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#1031]
**What Happened**
A user received a notification that their Speed / Volume ATR study request at [Shoreham Dr: Gosford Blvd – Hullmar Park Trl](https://move.intra.prod-toronto.ca/view/location/s1:ArPTlD/POINTS) was complete. When they go to that location in MOVE, no study data is available.

**What Should Happen**
Study data should be available at the specified location.

**To Reproduce**
Steps to reproduce the bug:
1. Go to [Shoreham Dr: Gosford Blvd – Hullmar Park Trl](https://move.intra.prod-toronto.ca/view/location/s1:ArPTlD/POINTS)
2. Scroll down to 'Studies'
4. See error (zero studies available at this location)

**Screenshots**
n/a

**Additional Notes**
Study requests at this location:
- [#214](https://move.intra.prod-toronto.ca/requests/study/214)
- [#469](https://move.intra.prod-toronto.ca/requests/study/469)

**Comment by candu** [comment]
Confirmed that this data is available in FLOW at stations "SHOREHAM DR E/B W OF GOSFORD BLVD" (arterycode 41562) and "SHOREHAM DR W/B W OF GOSFORD BLVD" (arterycode 41563).

This appears to be a conflation issue:

```sql
flashcrow=> select * from counts.arteries_centreline where arterycode in (41562, 41563);
 arterycode | centreline_type | centreline_id | direction |                        geom
------------+-----------------+---------------+-----------+----------------------------------------------------
      41562 |                 |               |           | 0101000020E6100000D498D2119DE153C0CEB63AE545E24540
      41563 |                 |               |           | 0101000020E6100000D498D2119DE153C0CEB63AE545E24540
(2 rows)
```

Let's look closer at that geometry:

```sql
flashcrow=> select ST_AsEWKT('0101000020E6100000D498D2119DE153C0CEB63AE545E24540'::geometry);
                      st_asewkt
-----------------------------------------------------
 SRID=4326;POINT(-79.5252117687808 43.7677580391588)
(1 row)
```

This location does appear to be [right on Shoreham](https://goo.gl/maps/LGqzwbPXKPkWCLfH8) - what's going on?

```sql
flashcrow=> select * from counts.arteries_double_node where arterycode = 41562;
 arterycode | ftype |  fnode   | ttype |  tnode   | n |                        geom
------------+-------+----------+-------+----------+---+----------------------------------------------------
      41562 |     2 | 13448119 |     2 | 13447983 | 2 | 0101000020E6100000D498D2119DE153C0CEB63AE545E24540
(1 row)

flashcrow=> select * from counts.arteries_double_link where arterycode = 41562;
 arterycode | from_link_id | to_link_id | geo_id
------------+--------------+------------+--------
      41562 |     13448119 |   13447983 |
(1 row)
```

So we find both of its endpoints, but don't find a `geo_id` matching them.

**Comment by candu** [comment]
Meanwhile: these requests were submitted on [this midblock](https://move.intra.prod-toronto.ca/api/locations/byCentreline?s1=s1:ArPTlD), which has `centrelineId = 30054901`.

```sql
flashcrow=> select from_inter, to_interse from gis.centreline where centreline = 30054901;
 from_inter | to_interse
------------+------------
   13447983 |   30054900
(1 row)
```

That other intersection is indeed in the `centreline.intersections` table:

```sql
flashcrow=> select * from centreline.intersections where "centrelineId" = 30054900;
 centrelineId | centrelineType | classification |          description           | featureCode |                        geom                        |     lat      |      lng
--------------+----------------+----------------+--------------------------------+-------------+----------------------------------------------------+--------------+---------------
     30054900 |              2 | LSRSL          | Shoreham Dr / Hullmar Park Trl |      504000 | 0101000020E6100000EF9F2A83A3E153C0766417D242E24540 | 43.767664205 | -79.525605003
(1 row)
```

However, the arterycodes appear to be coded to the whole Gosford to Bamford section:

```sql
flashcrow=> select * from centreline.intersections where "centrelineId" = 13448119;
 centrelineId | centrelineType | classification |        description         | featureCode |                        geom                        |     lat      |      lng
--------------+----------------+----------------+----------------------------+-------------+----------------------------------------------------+--------------+---------------
     13448119 |              2 | MNRSL          | Shoreham Dr / Bamford Cres |      501300 | 0101000020E610000097ACF70CC2E153C0AC6EA45535E24540 | 43.767252641 | -79.527468912
(1 row)
```

**Comment by candu** [comment]
We have a couple of options here.

One is to add a manual override for these arterycodes (see [this script](https://github.com/CityofToronto/bdit_move_etl/blob/master/scripts/airflow/tasks/arteries_geocoding/A1_arteries_manual_corr.sh) for how those are managed).

Another is to try and detect cases like this, where the arterycodes match _one_ endpoint of a midblock but not the other.  We don't yet handle that (see [this script](https://github.com/CityofToronto/bdit_move_etl/blob/master/scripts/airflow/tasks/arteries_geocoding/D/D1_arteries_centreline_table.sql) for steps), but broadly speaking this would entail:

- list all candidate midblocks (i.e. where one of `from_inter`, `to_interse` matches);
- find the best candidate according to some ranking / metric.

Here the best candidate could be the closest spatial match to `geom` (which should be efficient, as it can use spatial indexes).  There are quite a few arterycodes that could benefit from this:

```sql
flashcrow=> select count(*) from counts.arteries_centreline where geom is not null and centreline_id is null;                                                                            
 count
-------
   763
(1 row)
```

**Comment by candu** [comment]
Confirmed that these studies are visible in MOVE prod post-v1.6 release - closing out.
