### ISSUE TITLE
Preserve line breaks in comments and notes

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#1032]
**Description**
For notes and comments on study requests, preserve line break characters (`\n`).

**Acceptance Criteria**
Line breaks should be captured and displayed in the following cases:
- Notes on single requests
- Notes on bulk requests ("projects")
- Comments on any requests

**Additional Notes**
n/a

**Comment by candu** [comment]
See, e.g., `FcCommentsStudyRequest` for comments - we use `{{ comment.comment }}` in the component template, and the default handling of newlines in HTML is (IIRC) to replace them by a single space.

[This StackOverflow answer](https://stackoverflow.com/questions/36729634/rendering-newline-character-in-vuejs) has a potential solution: use `white-space: pre-line;` in CSS on the element used to render text.
