### ISSUE TITLE
"Project Complete" email is sent twice

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#1033]
**What Happened**
Two "project complete" emails are sent when a project (bulk request) is marked as complete.

**What Should Happen**
Only one "project complete" email should be sent.

**To Reproduce**
Steps to reproduce the bug:
1. Go to the MOVE map
2. Click on "View Data" for any location
3. Scroll down to "Studies"
4. Click on "Request New"
5. Add request details
6. Add at least one other study to the request
7. Add both studies to a project
*_Make sure to add yourself to the `additional emails subscribed` field!_
8. Log out
9. Log back in as a study supervisor
10. Mark your project requests as "Assigned"
11. Mark your project requests as "Completed"
12. See error: two "project complete" emails are sent

**Screenshots**
<img width="355" alt="Screenshot 2021-07-25 235430" src="https://user-images.githubusercontent.com/3179624/126930940-6c555278-0772-4750-b7a9-ee0bf515e217.png">

**Additional Notes**
@radumas reported this a couple weeks ago (thanks Raph!). I was able to reproduce the bug in QA.

**Comment by candu** [comment]
This is odd - in `EmailBase#getOptions`, we _do_ try to remove duplicates using `Array.from(new Set(recipients))`.

Is it possible that it's sending one such email for each request in the project?  (I haven't investigated further myself, but that's one possibility that comes to mind.)

**Comment by mkewins** [comment]
Couldn't reproduce, and no further reports of this.
