### ISSUE TITLE
Track Requests: "Assigned" filter matches assigned and completed requests

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#1046]
**What Happened**
In Track Requests, the "Assigned" request status filter appears to match both assigned and completed requests.

**What Should Happen**
The "Assigned" request status filter should only match assigned requests, and not completed requests.

**To Reproduce**
Steps to reproduce the bug:
1. Go to MOVE prod and log in;
2. Go to Track Requests in the left navbar;
3. Click "Filter";
4. Find the "Assigned" filter, select it, and "Save";
5. Page through search results

At this point, you'll see completed requests mixed in with the assigned requests.

**Screenshots**
![Track Requests with Assigned filter; both assigned and completed requests match](https://user-images.githubusercontent.com/151605/130090776-4a07de9b-19b2-4e17-99f5-d4285e19cae8.png)

**Comment by mkewins** [comment]
I notice that this only happens with bulk studies (aka projects), not individual requests.

**Comment by mkewins** [comment]
This may be fixed with our next web release.

**Comment by leonL** [comment]
Migrated to Jira board. Closing issue.
