### ISSUE TITLE
Download data for requests / projects

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#1051]
**Description**
@radumas requested the following:

> How do I download data from this page? https://move.intra.prod-toronto.ca/requests/study/bulk/16

**Acceptance Criteria**
- [ ] on View Request pages:
  - [ ] if the request is completed:
    - [ ] a "Download Data" button is shown;
    - [ ] clicking that button initiates a bulk export flow that downloads reports for the study associated with the request;
  - [ ] if the request is not completed, the user cannot download data from View Request;
- [ ] on View Project pages:
  - [ ] if the project is completed:
    - [ ] a "Download Data" button is shown;
    - [ ] clicking that button initiates a bulk export flow that downloads reports for all studies associated with requests in the project;
  - [ ] if the project is not completed, the user cannot download data from View Project.

**Additional Notes**
This might be a good follow-up task to #768 - maybe a "Download Data" button here could drop the user into whatever flow we build there?  Alternatively we could build this as a standalone flow, but it's probably worth investing dev time in better data export tools anyways...

The notion of "associated request" needs to be defined here; we don't currently have an explicit linkage between requests and the studies they result in.  One possible way to identify which study is associated with a request is as the next study after the request submission date that matches the request parameters (location, study type, days of week, etc.)

**Comment by mkewins** [comment]
If we have to guess the report that's associated with a request, I'd rather keep it simple and just redirect the user to the View Data page for that location, and let the user see what data is available.

**Comment by mkewins** [comment]
Closing this for now, because this is not currently aligned with our Roadmap and objective of getting to parity with CRASH and FLOW.
