### ISSUE TITLE
Store web application logs to EFS mount

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#1060]
**Description**
Right now, our web application logs are stored in `/var/app` on our `web` EC2 instances.  However, since we don't have SSH access to `web` in QA or prod, this means we can't access the live application logs from MOVE (except in dev)!  This in turn makes it harder to understand how users are using our backend services.

This task aims to move those logs to the EFS mount at `/data`, so that we can access them more readily.

**Acceptance Criteria**
- [x] update `scripts/deployment/web/forever.json` to store logs to `/data/log/web`, instead of `/var/app/log`;
- [x] verify that logs are being written to the new location;
- [x] add `logrotate` config to limit storage to last 30 days.

**Additional Notes**
`logrotate` configuration is managed [here in the `bdit_move_etl` repo](https://github.com/CityofToronto/bdit_move_etl/tree/master/scripts/deployment/etl/logrotate).

Note that EFS I/O is significantly slower than local disk; we should test performance in dev / QA to ensure there isn't too much impact.  (If there is, we may need to instead write logs to `/var/app/log` as now, and use `logrotate` to archive these into `/data` periodically.  However, that would involve changes to our `web` CloudFormation template.)

**Comment by candu** [comment]
@peter-lyons - similar to #1061 , this is a good task for getting used to our AWS infrastructure.  In this case, it'll also help us take a step towards better monitoring / analytics of MOVE (see also #978 for the big-picture umbrella task there), and it'll introduce you to the `bdit_flashcrow` repo that stores our web application code.

**Comment by peter-lyons** [comment]
@candu Issue looks to be resolved, logs are writing to the new location.
