### ISSUE TITLE
Store Airflow logs to EFS mount

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#1061]
**Description**
Right now, our Airflow logs are stored in `~/airflow/logs` on our `etl` EC2 instances.  However, our `etl` instances have limited disk space available (~10 GB as of time of writing), which means we can only retain a few days of logs.  (The Airflow scheduler writes a _lot_ of log messages.)

This task aims to move those logs to the EFS mount at `/data`, so that we can reduce disk usage on `etl`.

**Acceptance Criteria**
- [x] update [`airflow.cfg`](https://github.com/CityofToronto/bdit_move_etl/blob/master/scripts/deployment/etl/airflow.cfg) to store logs to `/data/log/etl`, instead of `~/airflow/logs`;
- [x] verify that logs are being written to the new location;
- [x] delete the old log folder at `~/airflow/logs`;
- [x] update the `airflow_log_cleanup` DAG to increase retention to 30 days.

**Additional Notes**
The [`airflow_log_cleanup` DAG](https://github.com/CityofToronto/bdit_move_etl/blob/master/scripts/airflow/dags/airflow_log_cleanup.py#L22) cleans up our Airflow logs daily, ensuring that we only retain a limited number of days.  This should automatically pick up any changes to the `BASE_LOG_FOLDER` setting in `airflow.cfg`.

**Comment by candu** [comment]
Assigning to @peter-lyons - this is a good first task for poking around our Airflow configuration and ETL machines.

**Comment by peter-lyons** [comment]
airflow component done and tested in dev
