### ISSUE TITLE
Configuration bug in bdit_move_etl requirements.txt

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#1073]
**What Happened**
When installing Airflow as per [these instructions](https://www.notion.so/bditto/Airflow-installation-6e378d9000994e08abfd28c64c7714de), we get an error related to the `cryptography` module.

**What Should Happen**
A clear and concise description of what you would expect to happen if the bug were fixed.

**To Reproduce**
Steps to reproduce the bug:
1. Find a new EC2 instance
2. Run through the Airflow installation process on it

This will fail with the above error, forcing the ops person to run `pip install cryptography` manually.

**Additional Notes**
In `requirements.txt` within the `bdit_move_etl` repo, `cryptography=3.1.1` is listed, but the current version is [`35.0.0`](https://pypi.org/project/cryptography/) - it's likely that this leads to a version expectation mismatch when installing `apache-airflow`.

**Comment by peter-lyons** [comment]
ported to jira
