### ISSUE TITLE
Location API for improved location search

### ISSUE THREAD

**Issue by chelsrosic** [CityofToronto/bdit_flashcrow#139]
**Description**
Improve location API to pull from appropriate source once a suggestion is clicked. Return a location and information associated with it using output from query suggestion table #136 when appropriate, and to pull from GCC geocoding location API when appropriate. 

**Acceptance Criteria**
- [x] traffic signal and pedestrian crossover location information can be pulled up using this API
- [x] API works with the GCC geocoding location service

**Comment by candu** [comment]
Closing this - the work in #392 and #393 helps address the integration part, and we'll open more specific tasks to get specific data sources added to location search.
