### ISSUE TITLE
Add midblocks to new location search

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#402]
**Description**
#401 describes the process for adding traffic signals and artery / station codes to new location search.

This task extends that work to include midblock search.

**Acceptance Criteria**
- [ ] build `location_search.centreline`, which combines `gis.centreline` and `gis.centreline_intersection` text to build search terms for each midblock;
- [ ] add `location_search.centreline` to `dev_data` dump;
- [ ] implement `LocationSearchDAO.midblockSuggestions` to query `location_search.centreline`;
- [ ] implement search ranking to combine intersections and midblocks (see ideas below).

**Additional Notes**
Why are midblocks more complicated than intersections?  In database, these only have the name of the street, which leads to situations like this:

```sql
select count(*) from gis.centreline where lf_name like 'Bloor St %';
 count 
-------
   214
```

That's right: if you search "Bloor St", there are over 200 candidates!  To narrow down further, we need cross streets (e.g. "Bloor and X", or "Bloor between X and Y").

This introduces another wrinkle: `gis.centreline` doesn't include those cross streets.  That means we have to join against `gis.centreline_intersection` on `fnode = int_id` and `tnode = int_id`, then include the resulting `intersec5` text in the search term for that midblock.

We also have to deal with ranking.  Under this scheme, queries like "Bloor and X" and "Bloor between X and Y" will match both intersections and midblocks: which are more important?  We'll need some heuristic to resolve that, for which there are several possibilities:

- just compute text matching scores on both, and rank by that score across both sets;
- always show intersections, then midblocks (or vice versa);
- use prepositions like "and", "between" from the search query to pick which set to prefer.

In addition, we'll have both exact and approximate matches across all sources - we'll likely want exact to be prioritized over approximate, no matter which source they come from.  This means tagging results with the source they came from and an exact flag, then using that within `LocationController.getLocationSuggestions` to combine these.

**Comment by candu** [comment]
Marking as WONTFIX - there's a lot of nuance here, and it's likely to add more confusion / complexity than value.

**Comment by mkewins** [comment]
interesting; i noticed this the other day (that midblocks aren't searchable, and you have to navigate to the nearest intersection). @candu did this issue come from a specific request or observation?

**Comment by candu** [comment]
@mkewins not that I recall.

this decision has been added to [our FAQs](https://www.notion.so/bditto/FAQs-9d6526e8d84d4abc90d43d4cdaba14e2), along with a couple of other explanations on special search terms.
