### ISSUE TITLE
Legend overlaps report menus on smaller screens

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#455]
**What Happened**
@jwrcoleman @mkewins @shinechaudhuri have all previously noted an issue where the map legend overlaps report menus (e.g. selecting the study date) in View Reports when using MOVE on smaller screens.

**What Should Happen**
The legend and report controls should not conflict.

**To Reproduce**
Steps to reproduce the bug:
1. On the map, navigate to any location with available studies and click "View Data";
2. Click "View Reports" beside any of the study types;
3. Resize your browser window, reducing the height until the issue appears.

**Screenshots**
From @jwrcoleman , the bug in action:

![image (6)](https://user-images.githubusercontent.com/151605/82045150-99e11e80-967c-11ea-9d69-f3b91fed6d34.png)

Note that the legend is _also_ obscuring several of the bottom-right map controls.

What it looks like on larger screens:

![image](https://user-images.githubusercontent.com/151605/82045534-40c5ba80-967d-11ea-837f-bf2013e9b9bd.png)

**Additional Notes**
As noted, we can mimic having a smaller screen by resizing the browser window.  The effective height of the window is given by `window.innerHeight`.  Some rough breakpoints here:

- `window.innerHeight === 875` is roughly the smallest height at which the layout still looks "normal" with no overlap;
- past that, the legend starts to overlap more and more of the map controls;
- at `window.innerHeight === 632`, the legend is starting to bleed down into the report drawer.

Similar to usual responsive breakpoints, which depend on window width, we can also [set breakpoints on height](https://stackoverflow.com/questions/43786717/vertical-responsive-height) - this is one potential way of fixing this.

**Comment by candu** [comment]
One possible solution: similar to how we collapse the search bar in View Reports, we could collapse the legend as well - e.g. into a button that triggers a dialog with the full legend content.

**Comment by mkewins** [comment]
Mateen at Vision Zero reported this issue as well on June 19th.
