### ISSUE TITLE
Beta prep: collision layer usability

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#645]
**Description**
From QA / usability testing:

> find that the collisions are always getting in the way of me selecting intersections.

This concern has been echoed by multiple users - adding a task here to fix that.

**Acceptance Criteria**
- [x] collision layer usability:
  - [x] for edit locations, request study, view request, edit request: save previous collision layer state, and create new legend state with collisions turned off;
  - [x] for all other actions: restore collision layer state;

**Additional Notes**
This probably just means having _two_ `legendOptions` states in our `vuex` store - one "collisions disabled on entry" one for these actions, one "normal" one for other actions.  Under such a setup, when entering such a page / mode we would copy `legendOptions` over to `legendOptionsDefaultNoCollisions`, but with the collisions layer disabled; when entering other pages / modes we would restore `legendOptions`.

**Comment by mkewins** [comment]
Another example of this today when on the phone with Adam from Vision Zero. Adam was editing a multi-location selection and was having difficulty selecting the intersection to add to the selection through all of the collisions, studies, and traffic volume on the map.
