### ISSUE TITLE
Infinite loading spinner when removing last location from multi-location selector

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#673]
**What Happened**
When removing the last location from the multi-location selector in Edit Locations mode, the page appears to load indefinitely, with no empty state shown.

**What Should Happen**
The user should not be able to remove the last location via Edit Locations.  (Either that, or we should at least show an empty state here.)

**To Reproduce**
Steps to reproduce the bug:
1. Go to any location in MOVE (e.g. [from the bug report](https://move.intra.dev-toronto.ca/view/location/s1:A2QvmBASvmB/POINTS))
2. Click on "Edit Locations"
3. Remove all locations

When you remove the last location, the loading bar shows indefinitely, and no empty state is ever shown.

**Screenshots**
![indefinite loading with no empty state in Edit Locations mode](https://user-images.githubusercontent.com/151605/96456115-122fab00-11ec-11eb-948c-efec223e6eee.png)

**Comment by mkewins** [comment]
Related to #847 (usually I get into the infinite loading spinner state when trying to clear the selected locations).
