### ISSUE TITLE
Better "conflation guidance" for collisions

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#726]
**Description**
At least 2 users have reported confusion around why collisions that appear to be along a midblock don't show up in View Data statistics.

The underlying reason is that collisions are preferentially tied to intersections within 30m, _then_ to midblocks within 30m.  This is similar to what CRASH does, but we don't have any way for the user to see a visual indication of this on the map (e.g. radius "bubbles" around intersections, colouring / highlighting of collisions, etc.)

**Acceptance Criteria**
- [ ] some form of "conflation guidance" is shown on the map;
- [ ] this guidance is tested with users.

**Comment by mkewins** [comment]
Related: "Improve display of collisions on the map" on our feedback/features board.

**Comment by candu** [comment]
Marking this as closed; I'll create a new set of issues for this mini-project, now that we've scoped it out in a bit more detail.
