### ISSUE TITLE
For multi-location Collision Directory reports, separate collisions by location

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#742]
**Description**
From user feedback:

> In collision data report, Directory Level, it is easier for the user to see the data in a separated format (like the one that Crash generates) based on the intersections and mid-blocks

**Acceptance Criteria**
- [ ] multi-location collision reports list collisions by location;
- [ ] single-location collision reports remain as they are now.

**Additional Notes**
See report requirements page on Notion for more details; do NOT attach collision reports here.

**Comment by mkewins** [comment]
Migrated to Jira.
