### ISSUE TITLE
OpenIdClient using UPN as email address, instead of EmailAddress

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#761]
**What Happened**
In our `OpenIdClient` wrapper, we use the `upn` claim as the email address, when we should be getting an `email` (or similar) claim.  Relevant quotes from ensuing discussion:

> DSTeam told us not to treat user principal names as email addresses – there’s a semantic difference.
> I can’t find anything in the City’s Directory Services Authentication Standard that specifically forbids using UPN as an email address (if an email address is associated with it – it isn’t always), but it does say that the Email attribute in AD should be used as the “source of truth”.

Further investigation reveals that tokens returned from ADFS do not include an `email` (or similar) claim - only `upn`.

**What Should Happen**
Tokens returned from ADFS should include an `email` (or similar) claim, and we should use that in `OpenIdClient` to retrieve the user's email address.

Since we've previously used `upn`, we should also update the `users` table on login even for existing users.  (A quick scan of the `users` table shows all users have `@toronto.ca` addresses, so this is more to be on the safe side than to fix a known issue.  Still, it's good practice, and it may future-proof MOVE a bit in case staff email addresses ever change.)

**To Reproduce**
Steps to reproduce the bug:
1. Run `npm run backend:inspect`, and set a breakpoint in `OpenIdClient` after the token is received;
2. Run other MOVE services locally, and log in;
3. Inspect the value of the token.

At this point, you should see that the token is returned, but does not contain an `email` (or similar) claim.

**Comment by candu** [comment]
Pulling this out of the release milestone - we should eventually address it, but it's not urgent at this point.

**Comment by leonL** [comment]
Migrate to Jira [MOVE-207]
