### ISSUE TITLE
TMC Summary Report inconsistent between FLOW and MOVE - Keele/Whitburn

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#765]
**What Happened**
The TMC Summary Report in FLOW has different values than those in MOVE for `Keele St / Whitburn Cres`.

**What Should Happen**
Report values in MOVE should match those in FLOW.

**To Reproduce**
Steps to reproduce the bug:
1. Go to `Keele St / Whitburn Cres` (TCS: 1255)
2. Open the most recent TMC Summary Report (Routine Hours - October 29, 2020)

**Screenshots**
n/a

**Additional Notes**
Examples of inconsistencies:
| Cell | Value in FLOW | Value in MOVE |
| --- | --- | --- |
| Off Hour Average* - Car - Northbound - Exits | 903 | 904 |
| PM Peak** - Truck - Northbound - Exits | 103 | 100 |

*The Off Hour Average is not explicitly stated in FLOW. In MOVE it's 10:00-15:00. Could there be a difference in time window causing this summation issue?

**The PM peak has a different range in FLOW (17:00-18:00) than MOVE (16:45-17:45). Could this have something to do with the numbers counted differently?

From what I can tell by glancing at the reports side-by-side, the inconsistencies seem to be concentrated in the "OFF HR AVG" and "PM PEAK" sections.

**Comment by candu** [comment]
More recent changes (e.g. #837 ) appear to have fixed this - marking closed.
