### ISSUE TITLE
Better selection tools for bulk export reports

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#768]
**Description**
From user feature request (thanks @jwrcoleman !):

> Final reflection on my multi-download. Would be nice to be able to specify what types of reports you want (summary, detailed, intersection summary) and file types (pdf, csv or both). In this case I wanted pdf and csv, and only the summary reports for example, and did this with two separate downloads and then deleted all the other report types I didn't need.

**Acceptance Criteria**
- [ ] when exporting study reports in bulk, the user can filter by report type.

**Additional Notes**
Report type and study type are linked, so this may need to live in the studies accordion.

There might be some impact here from upcoming work on filtering across map and View Data (in that this might lead to reorganizing information in View Data) - so probably best tackled after that.

**Comment by mkewins** [comment]
Migrated to Jira.
