### ISSUE TITLE
Different collision numbers from CRASH

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#778]
**What Happened**
Karen reported a discrepancy in collisions - total and verified - between CRASH and MOVE along Sheppard from Beecroft (`px:1169`) to Leslie (`px:744`).

**What Should Happen**
I'm unsure whether the numbers should match exactly, but we should get to the bottom of why they're different.

**To Reproduce**
Steps to reproduce:
1. In multi-location mode, select a corridor from `Sheppard / Beecroft` to `Sheppard / Leslie` (inclusive)
2. Save the selection and go to the View Data page
3. Filter collisions by date: 1/1/2015 to 12/31/2019
4. Observe 2665 total collisions and 608 verified

For the same selection and date filter, Karen reported 495 verified and 2630 total. (I haven't been able to confirm this because I'm struggling with CRASH.)

A very specific example of this difference can be seen at `Sheppard Ave E: Doris Ave – Bonnington Pl` for the same date range:
* MOVE reports 3 verified / 5 total
* CRASH reports 2 verified / 5 total

The collision ID numbers are the same for the five collisions. The only difference is the collision that occurred in December 2015 was marked as verified in MOVE, but not in CRASH.

**Screenshots**
n/a

**Additional Notes**
In CRASH, I noticed a small line of text that indicates CRASH uses a 20m radius around intersections, where I believe we're using a 30m radius in MOVE.

**Comment by candu** [comment]
Found additional evidence suggesting that CRASH uses a 20m buffer - the CRASH source code refers to a setting `buffer_size_m`, which is loaded from an MS Access database (!) in the application folder called `Local.mdb`.  I couldn't open the file in MS Access itself, as it was created using an ancient version that's no longer supported; however, a quick search of this file in a text editor suggests `buffer_size_m` is set to 20m.

I'll update the pipelines accordingly.

**Comment by candu** [comment]
After changing the buffer radius to 20m, the total number of collisions is a bit closer in MOVE (2653 now), but the number of validated collisions remains high as compared to MOVE.

Found what looks like the source of the discrepancy between 3 / 5 verified (in MOVE) and 2 / 5 verified (in CRASH), by looking at the database records directly.  (I tried locating the logic in CRASH source code, but couldn't manage to track that down.)

In `collisions.events` (MOVE) / `"TRAFFIC"."ACC"` (CRASH), there are 3 possible values for `changed`:

- `NULL`: this record has never been verified;
- `0`: this record has been partially verified (i.e. someone in Data Collection looked at it, but only checked a subset of the fields);
- `-1`: this record has been fully verified.

The discrepancy here is in a collision record where `changed = 0`: MOVE considers this validated, CRASH does not.

To reduce confusion, I'll change MOVE to only consider collisions as validated if `changed === -1`.

**Comment by candu** [comment]
Deployed updates; aggregate numbers now look closer (2653 / 538), and Sheppard: Doris - Bonnington now shows 2 / 5 validated in MOVE.

In general, though, these numbers won't match 100% exactly, for any of a number of reasons.  CRASH is built against pre-centreline maps, and the geometry of intersections / midblocks will differ slightly - for instance, much better surveying / satellite imagery is available now.  There may also be slight differences in projection - GCC's guidelines on which projection to use for distance comparisons (e.g. collision buffering around intersections / midblocks) have changed.  Geospatial databases have changed, so distance functions could have changed: there's exact approaches using great circle arcs, and a bunch of ways to approximate distance.  There could even be differences in the precision of stored coordinates - it was at one point commonplace to use single-precision floating-point values for a lot of things, mostly to save on memory / disk usage; double-precision is often used now that memory / disk are much cheaper.

I'm not sure how best to communicate this to our users, but truly, fully getting to the bottom of why these values differ is actually a _lot_ of work.

Anyways: marking closed for now, and we can reopen more specific tasks if we come across glaring inconsistencies.
