### ISSUE TITLE
View Reports: see all available studies (non-permanent)

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#784]
**Description**
In View Reports, MOVE currently offers access only to the 10 most recent studies of a given type.  For example, if there are 27 TMCs (e.g. at Don Mills / Eglinton), the user can only access the last 10 TMCs; the other 17 are currently inaccessible.

While this is also an issue for permanent counting stations (e.g. RESCU), this task is only about solving this for other locations.  Permanent counting stations have large histories of count data, and will likely require an entirely new interface; other locations do not have this problem, and user needs can likely be met with small changes to the existing interface.

**Acceptance Criteria**
- [ ] for study locations / types without permanent stations, users can access all historical studies of that type at that location;
- [ ] for study locations / types with permanent stations, keep the current setup for now.

**Comment by mkewins** [comment]
We haven't heard any feedback about this in well over a year. This may be something we revisit in the future.
