### ISSUE TITLE
Data sidebar blank upon returning from download manager

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#785]
**What Happened**
From user report (thanks @jwrcoleman !):

> When I go back and from the download manager to the map, the data sidebar ends up blank.

**What Should Happen**
The map and data sidebar should retain the previously selected location.

**To Reproduce**
Still looking for a reliable repro; add details when found.  Initial guess is that this is an issue with frontend states.

**Comment by mkewins** [comment]
Tested on Firefox (88.0.1 (32-bit)). Couldn't reproduce; closing.
