### ISSUE TITLE
Improvements to study request management

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#794]
**Description**
We've received a lot of great feedback from our users in Data Collection on how to improve study request management.  This task tracks progress there, since this consists of a few smaller tasks.

**Acceptance Criteria**
- [x] remove `canTransitionTo`, transition restrictions;
- [x] allow users to search for a request by ID in Track Requests;
- [x] improve info hierarchy in View Request page (see [this page on Notion (internal only)](https://www.notion.so/bditto/Problems-with-information-hierarchy-in-study-request-details-b3203972fcd648f7812f7e058f833f99));
- [x] include `assignedTo` and `ccEmails` details in View Requests.

**Comment by mkewins** [comment]
@candu to clarify: should the 3rd item be "filter by request ID" instead of "search for a request by ID"?
