### ISSUE TITLE
Study requests: additional study types

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#795]
**Description**
Several users have tried to request study types that are not currently included in our `StudyType` enum.  We've also made incorrect assumptions about where some study types are performed - for instance, Ped Delays.

This task adds a couple of frequently-requested study types to our list, and also adds an "Other" option for cases where an unusual or new study type needs to be performed.

**Acceptance Criteria**
- [x] allow users to submit requests for Ped Delays at intersections;
  - [x] Ped Delays: hours or duration?
- [x] add "Other" option for study type;
- [x] allow users to create "Other" study requests at both intersections and midblocks;
- [x] when users select "Other" as the study type:
  - [x] show a text field that allows them to enter the study type, and make that field required;
  - [x] hide both hours and duration, and force the user to enter additional details;
- [x] add a `studyTypeOther` field to database records, and default to `NULL` for existing study requests;
- [x] ensure that `studyTypeOther` is in validations, and that test cases include this field.

**Additional Notes**
This strikes a deliberate balance between offering admin management of study types and our current "only these study types can be used" approach.  Under this new approach, study types can be "promoted" over time through subsequent releases:

- first, a new study type will be entered under "Other";
- if many people are requesting this study type, we can add an explicit option for it, and go back and mark those requests with that new option;
- eventually, MOVE will also incorporate data, reports, etc. from that type of study.

**Comment by jwrcoleman** [comment]
Would like a quick conversation about the ATR side. I re-read our data collection contract and it reads that classification is an output from speed/volume ATRs that can be requested any time. Meaning it isn't speed/volume OR classification like I originally understood it. So this could actually just be a checkbox under speed/volume:

- [ ]  Provide vehicle classification (or something like that)

(It might even make more sense to have them all as subsets of ATR as it just feels like this is an option within an ATR count)

**Comment by mkewins** [comment]
@jwrcoleman flagged that data collection also gets `School Crossing Guard Count` requests often.

> It's essentially a TMC with extra manual counting of school-aged children.

If I can get answers to the following questions soon, would like to add this alongside `Ped Delay` and `Classification` changes (although it sounds like there are decisions needed for the `Classification ATR` as well, per Jesse's comment above).

* request options (same as TMC options? school hours by default? default days these are usually done?)
* can we add this as an option to TMC? or should this be a dedicated request type?
