### ISSUE TITLE
Possible rounding issue with totals in TMC Summary Report

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#799]
**What Happened**
The totals aren't adding up correctly in the TMC Summary Report.

**What Should Happen**
Staff shouldn't question the validity of these values, totals should make sense. We have a few paths forward: make sure the addition of integers is calculated as expected (e.g. 1+2=3) OR we should show decimals (e.g. 0.8 + 1.6 = 2.4) OR we add a disclaimer that these values are rounded and leave the values as-is (e.g. 1+2=2). Each of these approaches have pros/cons.

**To Reproduce**
Steps to reproduce the bug:
1. Go to `Palmerston / College`
2. Open the most recent TMC Summary Report
3. Scroll down to the `OFF HR AVG` section

Under `NORTHBOUND` approach, `TRUCK` mode, movements `Left` = 1, `Thru` = 0, `Right` = 2, and the `Total` (which is the sum of these values) is 2, where you'd expect to see 3.

Similarly, the totals for `PED` and `BIKE` are off by a few integers as well.

**Screenshots**
![Screenshot 2021-02-18 173502](https://user-images.githubusercontent.com/3179624/108430676-bca5f200-720f-11eb-8fca-c3e9a7a65b27.png)

**Additional Notes**
Chatted with @candu about this briefly; this may be due to a rounding issue.

Possible solutions:
* Add the rounded values to get the total (guessing this is what FLOW does)
* Keep the totals as-is and add a disclaimer
* Use decimals for small numbers

@aharpalaniTO suggested drawing up these three options and putting out a survey to see which option staff prefer (going to do this!).

Also need to talk with @jwrcoleman about whether accuracy vs. a cleaner, simpler visual display is more important. The bottom line is an inconsistency like this can lead to lower trust in the data (not good).

**Comment by candu** [comment]
This was fixed by #837 - marking closed.
