### ISSUE TITLE
500 error trying to load warrant report

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#815]
**What Happened**
The `/reporter/reports` endpoint returns a 500 error trying to load the warrant report for `Fasken Dr: near 427 N Fasken Ramp`.

**What Should Happen**
The warrant report should load.

**To Reproduce**
Steps to reproduce the bug:
1. Go to `Fasken Dr: near 427 N Fasken Ramp` (URL endpoint: `/view/location/s1:An27GA/POINTS`)
2. Click on 'View Reports'
3. Scroll over to the 'Warrant Report' section
4. Generate a warrant

**Screenshots**
Request
`/reporter/reports?type=WARRANT_TRAFFIC_SIGNAL_CONTROL&id=5%2F39725&format=WEB&adequateTrial=true&isTwoLane=true&isXIntersection=true&preventablesByYear=0&preventablesByYear=0&preventablesByYear=0&startDate=2018-02-24%2015%3A36%3A32.036`

Response
`{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}`

**Additional Notes**
n/a

**Comment by candu** [comment]
Fixed by updates in #823 , marking closed.
