### ISSUE TITLE
Study type and details missing from midblock request flow

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#819]
**What Happened**
The study request flow for mid-block locations is missing the study type and details request information.

**What Should Happen**
When requesting a mid-block study, users should see options to select the study type and fill in study details.

**To Reproduce**
Steps to reproduce the bug:
1. Search for any mid-block location
2. Navigate to View Data for that location
3. Select the "Request New" button
4. See missing study type/details when in the request flow

**Screenshots**
<img width="779" alt="Screenshot 2021-02-25 154323" src="https://user-images.githubusercontent.com/3179624/109214760-3b56de00-7780-11eb-9719-94a37e93a53a.png">

**Additional Notes**
Happening in QA
This is release-blocking (P0), must fix before Release 1.2 goes out

**Comment by candu** [comment]
Found a similar bug in the bulk Request Study flow:

![study details missing in "Review and Submit" phase of bulk Request Study](https://user-images.githubusercontent.com/151605/109225122-d9e83c80-778a-11eb-96ed-fcca71f7cb03.png)

From dev console:

```
vue.runtime.esm.js:1888 TypeError: Cannot read property 'other' of null
    at o (FcStudyRequestStudyType.vue?dfd3:1)
   ...

vue.runtime.esm.js:1888 TypeError: Cannot read property 'studyType' of undefined
    at o.yt (FcCardStudyRequestConfirm.vue?677d:1)
    ...
```

(Looks related to recent updates around "other" study type.)
