### ISSUE TITLE
TMC Intersection Summary report fails to load at Queensway/near High Street intersection

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#834]
**What Happened**
The TMC Intersection Summary report is failing to load at [Queensway/near High Street](https://move.intra.prod-toronto.ca/view/location/s1:Alu9GA/POINTS/reports/TMC)

**What Should Happen**
The TMC Intersection Summary report should load

**To Reproduce**
Steps to reproduce the bug:
1. Go to [Queensway near High Street](https://move.intra.prod-toronto.ca/view/location/s1:Alu9GA/POINTS)
2. Beside "Turning Movement Count" click on "View Reports"
3. Select the "Intersection Summary Report" tab
4. See error (infinite loading wheel)

**Screenshots**
![Screenshot 2021-03-16 122826](https://user-images.githubusercontent.com/3179624/111345073-50be7a00-8653-11eb-8eb4-2e8595de4468.png)
![Screenshot 2021-03-16 122925](https://user-images.githubusercontent.com/3179624/111345077-51571080-8653-11eb-9b58-f0ac452ff5ef.png)

**Additional Notes**
This also looks like a location where there is an intersection out of a shopping mall complex, but it's only represented as a single midblock.

**Comment by candu** [comment]
This is [already fixed in QA](https://move.intra.qa-toronto.ca/view/location/s1:Alu9GA/POINTS/reports/TMC).
