### ISSUE TITLE
Can't sort the requests table by headers

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#851]
**What Happened**
When I click on the track request table headers, the table isn't being sorted.

**What Should Happen**
Clicking on the headers should sort the table.

**To Reproduce**
Steps to reproduce the bug:
1. Go to the Track Requests page
2. Authenticate if needed
3. Click on any of the table headers to sort the table by that header (ascending/descending)

**Screenshots**
![Screenshot 2021-03-23 162659](https://user-images.githubusercontent.com/3179624/112213675-b7fca100-8bf4-11eb-8a74-f0a76686ce72.png)

**Additional Notes**
I wonder if this is happening since we now have people requesting counts with the type of "Other" (we introduced this in the last release).

**Comment by candu** [comment]
This should be fixed by previous work on #858 , marking closed.
