### ISSUE TITLE
PX 211 attached to the wrong segment

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#853]
**What Happened**
PX 211 is getting assigned to the wrong segment ([Gardiner Expressway](https://move.intra.dev-toronto.ca/view/location/s1:AzxvIA/POINTS)).

**What Should Happen**
PX 211 should be assigned to the intersection of [Lakeshore / Yonge](https://move.intra.dev-toronto.ca/view/location/s1:AaAwmB/POINTS).

**To Reproduce**
Steps to reproduce the bug:
1. Search for PX 211
2. See that it's attached to the Gardiner, instead of the intersection node of Lakeshore/Yonge

**Screenshots**
![Jesse PX 211 bug](https://user-images.githubusercontent.com/3179624/112219459-6277c280-8bfb-11eb-94d7-800308893563.png)

**Additional Notes**
@jwrcoleman did some digging and said it might be related to arterycodes. This might be a similar/related issue to #775 but wanted to capture here anyway for posterity. Also because increasing numbers of these kinds of issues (missing intersections, inconsistencies with the centreline) might warrant more discussion on how to address edge cases. For example, could we work with GCC to report and update the centreline when we find issues?

**Comment by jwrcoleman** [comment]
I'm not familiar with the conflation process that brings in PX numbers, but if it is tagged to the wrong intersection ID in the source signalview data, we could contact Boris Guerkine to have it fixed.

**Comment by mkewins** [comment]
Since March 2021, we've made various updates to the conflation process. That must have impacted this intersection/PX, because I now see PX 211 tagged to Yonge / Lakeshore.

![Screenshot 2022-01-20 103702](https://user-images.githubusercontent.com/3179624/150370903-48173d7c-e5b2-4d6b-b34b-db9316c63b98.png)
