### ISSUE TITLE
Ensure we have analytics on filters, reports

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#861]
**Description**
We have analytics for page loads, button clicks, and similar interactions.  This task aims to ensure that we have rich analytics around which filters are actually being used.

**Acceptance Criteria**
- [ ] we capture analytics around global filters;
- [ ] we capture analytics around request filters, search, and sort;
- [ ] we capture analytics around report usage.

**Additional Notes**
This _may_ be doable by capturing analytics around REST API calls, either from `WebApi` or via a `hapi` request hook.  (After all, we're sending our own data collection events - why not do it from the backend, if that's easier?)

**Comment by mkewins** [comment]
Closing issue because we will pick up improved analytics as an epic in the future.
