### ISSUE TITLE
Track Requests Pagination: page number hidden if window size is too small

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#870]
**What Happened**
The page number selector is pushed down the page (and subsequently hidden) if the window size is too small. No scrollbar to scroll down to see it. (Gotta run, but will update with more details later.)

<img width="480" alt="Screenshot 2021-04-14 172829" src="https://user-images.githubusercontent.com/3179624/114787102-34deee80-9d4d-11eb-9501-bf5d85711d2f.png">

**What Should Happen**
A clear and concise description of what you would expect to happen if the bug were fixed.

**To Reproduce**
Steps to reproduce the bug:

**Screenshots**
For frontend bugs, provide a browser screenshot if possible.  For backend bugs, screenshots of either the frontend dev tools (e.g. Network tab showing API responses or errors, Console tab showing errors) or the backend `node --inspect` dev tools (e.g. Debugger tab showing the issue) are helpful.

**Additional Notes**

**Comment by candu** [comment]
@mkewins this may actually have to do with _resizing_ the browser - we don't have a resize handler on this page yet.  (To check this, I tested by using device mode in Chrome dev tools: this repro'd the bug, as expected, but after refreshing it rendered correctly in the smaller window.)
