### ISSUE TITLE
Sorting issues in Track Requests

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#872]
**What Happened**
From our [QA testing spreadsheet (internal only)](https://docs.google.com/spreadsheets/d/1ixtkOYs1RLO1DKO-7-_6MpnfNhEvSgRt70JUIstI6N0/edit#gid=1768524490), some notes about sorting missing from the study type and status columns:

> can't sort by study type anymore (in dev / qa)? can currently sort by study type in prod

> removed from this version? at the same time, i think this is more useful for filter than sort

**What Should Happen**
This is...a good question!  As noted, status is a better fit for filtering than sorting; the same may be true of study type.  This leaves us with a couple of options:

- decide that we're not going to offer sorting on one (or both) of these columns;
- decide what sorting should mean on these columns, especially where bulk requests are concerned, and implement that.

**To Reproduce**
Steps to reproduce the bug:
1. Log in as any user with `STUDY_REQUESTS` permissions;
2. Click on "Track Requests" in the left navbar.

At this point, the table shows up, but you cannot sort on study type or status.

**Additional Notes**
Needs input from @shinechaudhuri @mkewins on the right path forward.

The main challenges here are maintaining `study_request_items` (see Additional Notes in #871 for a fuller explanation) and figuring out what to do with bulk requests.

IMHO we should just not support sorting on these columns - if the intent is to find a specific type of study, that's what filters are for!

**Comment by jwrcoleman** [comment]
fwiw i agree on the sorting comment.. filters are better for that :)

**Comment by mkewins** [comment]
donna reported she uses to _sort_ most often (and exclusively) are:
- `id`
- `location`
- `requester` (but she didn't know there was a search by requester function)

i think `id` absolutely makes sense (also the default sort should be on id + descending, newest to oldest requests)

here's what makes the most sense to me with respect to headers, and how they'd be used (in sort / search / filter):
- `id` - sort / search
- `location` - search
- `study type` - filter
- `requester` - search
- `date requested` - sort / filter (anything requested between x and y dates)
- `assignee` - filter
- `expected by` - sort / filter (to find overdue requests, for example)
- `status` - filter

^^ this list might help answer #871, too. to me, search makes the most sense on id, location, requester fields.
