### ISSUE TITLE
Rename "Bicycle Volume ATR" to...?

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#873]
**What Happened**
From @jwrcoleman :

> One thing i uncovered with the new filters, is that studies in there listed as bicycle ATRs are actually Permanent Bicycle Counters. (on Sherbourne and Bloor/Castle Frank)

**What Should Happen**
The language around bicycle counts conducted by permanent counting stations should be clear.  There are a couple of ways we could approach this:

- just change "Bicycle Volume ATR" to something else;
- add further contextual help around the use of terms like this (e.g. a glossary somewhere in MOVE).

@jwrcoleman @mkewins should probably weigh in on the best path forward here.

**To Reproduce**
Steps to reproduce the bug:
1. Click "Edit" in the filters box;
2. Open the "Studies" section of the accordion at bottom of the resulting drawer.

At this point, you'll see the option to filter on "Bicycle Volume ATR" as a study type.

**Comment by mkewins** [comment]
I'm going to defer to @jwrcoleman on this one.

My main question would be: when is a "Bicycle Volume ATR" just an ATR vs. a permanent counter? Do we _do_ bicycle-only ATRs? Or would we collect a multi-modal ATR?

fwiw, this is intersecting with some work I'm doing to map out the hierarchy of studies / reports / warrants (so any info that can be shared about the nuance between these different types of studies would be helpful please!)

**Comment by mkewins** [comment]
I noticed a related issue when talking with Donna yesterday. Some locations with `Bicycle Volume ATRs` also have data loaded as `Volume ATRs` but it looks like the data is all coming from the same permanent bike counters.

Examples:
- [Bloor / Huron](https://move.intra.prod-toronto.ca/view/location/s1:Ah8tIA/POINTS)
- [Bloor / Markham](https://move.intra.prod-toronto.ca/view/location/s1:Ah3u_A/POINTS)
- [Sherbourne / Wellesley](https://move.intra.prod-toronto.ca/view/location/s1:Ah3u_A/POINTS)
- [Bloor / Castle Frank](https://move.intra.prod-toronto.ca/view/location/s1:ADOKBB/POINTS)

So a couple issues here:
1. If `Volume ATR` counts are exclusively counting bicycles, they should be classified as `Bicycle Volume ATR`. This difference most likely happened at the point of data loading.
2. Open question: how do we handle study type (i.e. `Bicycle Volume ATR`) and mechanism of collection (i.e. permanent count stations)?

On (2) -- we have a similar parallel with `Volume ATR` and `RESCU` (example at [DVP on-ramp south of Bloor](https://move.intra.prod-toronto.ca/view/location/s1:AJatIA/POINTS)), where the data is simply volume data collected at a permanent count station, but it's classified by the station type (RESCU) not the data type (Volume ATR). So maybe the solution here is to add a dedicated `Permanent Bicycle Counter` study type?

**Comment by jwrcoleman** [comment]
Couple quick thoughts
-these locations should be called bicycle permanent count stations (not ATRs), but if they were loaded wrong they really should all be bike counts as you note.
- we have a dataset of bicycle ATRs that we’d like to one day load from cycling
- Bicycle ATR is given as an option when requesting studies, but this is not a study type that we can deliver (OTI doesn’t do bicycle ATRs), so they should be removed from the request options.
- For rescu etc, I like the permanent count station typology here too (as opposed to calling them rescu)

**Comment by mkewins** [comment]
@jwrcoleman I'm moving this over to Jira to account for this in our product backlog. How can I communicate the need to re-load/re-classify these bike counts where they were uploaded as "Volume ATRs"?
