### ISSUE TITLE
Filter, search, sort, download on View Bulk Request table

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#880]
**Description**
In previous issues (#871 , #872 , #866 ) we implemented filter, search, sort, and download for Track Requests.  This task aims to enable as much of this functionality as possible inside View Bulk Request.

**Acceptance Criteria**
- [ ] search bar is added to View Bulk Request;
- [ ] filter button is added to View Bulk Request;
- [ ] download button is added to View Bulk Request;
- [ ] these controls work as in Track Requests, but only for the requests in that bulk request.

**Additional Notes**
For View Bulk Request, both "Download Selected" and "Download All" can use the `TRACK_REQUESTS_SELECTED` report type - we can just pass the list of all matching IDs in the latter case.

This will likely involve a new set of REST API endpoints and DAO methods, designed to filter / search / sort within a single bulk request.

**Comment by mkewins** [comment]
This is not aligned with current priorities. We may revisit in future.
