### ISSUE TITLE
Additional study management controls

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#883]
**Description**
Over the last while, we've received several feature requests around study management from @jwrcoleman and various users.  This task captures the lowest-hanging fruit among that feedback.

**Acceptance Criteria**
- [x] users with the given permissions:
  - [x] can change the requester of a study request... (`STUDY_REQUESTS_ADMIN`)
    - [x] the REST API permits this for non-bulk requests;
    - [x] the REST API permits this for bulk requests, in which case it changes the requester of all sub-requests as well;
    - [x] this is added as a test case in relevant test suites;
  - [x] can group several study requests into a single "project" (i.e. bulk request)... (`STUDY_REQUESTS`, `STUDY_REQUESTS_ADMIN`)
    - [x] a new REST API method for grouping requests into a bulk request is added (e.g. to `StudyRequestBulkController`);
    - [x] a new DAO method is added for this (e.g. in `StudyRequestBulkDAO`);
    - [x] this is added as a test case in relevant test suites;
    - [x] the frontend offers a way to do this (e.g. in Track Requests).
  - [x] can add one or more study requests to an existing "project" (i.e. bulk request)... (`STUDY_REQUESTS`, `STUDY_REQUESTS_ADMIN`)
    - [x] a new REST API method for adding requests to a bulk request is added;
    - [x] a new DAO method is added for this;
    - [x] this is added as a test case in relevant test suites;
    - [x] the frontend offers a way to do this (e.g. in Track Requests);
- [x] in all above cases, users without given permissions:
  - [x] cannot perform relevant REST API actions;
  - [x] cannot see relevant frontend UI in MOVE.

time permitting:
- [x] users with `STUDY_REQUESTS` scope:
  - [x] can change the location of a study request...
    - [x] the REST API permits this for requests;
    - [x] this is added as a test case in relevant test suites;
    - [x] the frontend offers a way to do this (e.g. in Edit Request).

**Additional Notes**
This might require a bit of design work from @shinechaudhuri - main concern here is interface clutter from adding these functions.  If we _do_ want to allow users to edit locations (unclear right now), we'll need design there as well.

This new functionality will likely mean no longer being able to show a "location selection" for bulk requests - we'll either have to get rid of that part of the bulk request, or change the map to just show a collection of points where study requests are taking place.

**Comment by mkewins** [comment]
One other improvement data collection asked for:

> Can I edit an assigned request?

Apparently sometimes data collection will change the request details after discussing with the contractor.

**Comment by candu** [comment]
Updated slightly to remove requirements around watch / unwatch UI, requester change UI - breaking those out into separate issues, since this one already has 4 PRs (and will soon have a fifth!)
