### ISSUE TITLE
Regular re-conflation of study requests

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#886]
**Description**
As the Toronto Centreline is updated over time, previously conflated study requests might be tied to a centreline feature that no longer exists.  This task aims to help address that by re-conflating these study requests.

**Acceptance Criteria**
- [ ] introduce a new data pipeline, e.g. `study_requests_geocoding`, that:
  - [ ] identifies study requests tied to a centreline feature that no longer exists;
  - [ ] re-conflates those study requests to the nearest centreline feature, if possible.
- [ ] schedule this pipeline to run after each centreline update.

**Additional Notes**
For now, let's keep the requirement that all study requests must have a non-`NULL` centreline location - this simplifies application code considerably in a bunch of places.  Together with #883 , this should provide users with enough tools to fix these issues over time.

**Comment by candu** [comment]
Query to identify study requests that aren't tied to a valid centreline location:

```sql
SELECT sr.id FROM study_requests sr
LEFT JOIN centreline.intersections ci USING ("centrelineType", "centrelineId")
LEFT JOIN centreline.midblocks cm USING ("centrelineType", "centrelineId")
WHERE ci."centrelineId" IS NULL AND cm."centrelineId" IS NULL;
```

We can expand this query further to re-conflate study requests, e.g. using similar queries to what we use for collision conflation (with `LATERAL JOIN`s against `centreline.intersections`, `centreline.midblocks`).

**Comment by peter-lyons** [comment]
moved to jira
