### ISSUE TITLE
Previously loaded ATR not visible in MOVE

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#905]
**What Happened**
From a user bug report:

> Some counts are not showing up in MOVE even though I loaded several days ago: ATR on blythewood between strathgowan cres and blythe hill road

Right now we run FLOW replication weekly, so this data should have appeared by now (the bug report is from Apr. 14, 2021) - but it hasn't.

**What Should Happen**
Data should be available in MOVE at most 1 week after being loaded in FLOW.

**To Reproduce**
Steps to reproduce the bug:
1. Go to [Blythwood Rd: near Blyth Hill Rd](https://move.intra.prod-toronto.ca/view/location/s1:A3J5SA/POINTS).

At this point, you can see that a Speed / Volume ATR has been requested, but no data is available.

**Screenshots**
![Blythwood Rd: near Blyth Hill Rd - study requested, but no data yet](https://user-images.githubusercontent.com/151605/117343126-f9c66b80-ae71-11eb-9e6b-168097445bc1.png)

**Additional Notes**
We'll need to investigate the whole chain here, right back to the Oracle database that backs FLOW: loading, replication, or conflation could have failed.  If that's the case, we'll also potentially need better monitoring here.

To fully investigate, we may need to know the underlying arterycode.

**Comment by candu** [comment]
FLOW shows a count at arterycode 29044 on 2021-03-18 - it's likely this is the count in question.  (This also means that the data is _definitely_ in Oracle.)

Some spelunking around our database.  First, does the arterycode exist?

```sql
flashcrow=> select "LOCATION" from "TRAFFIC"."ARTERYDATA" where "ARTERYCODE" = 29044;
               LOCATION
----------------------------------------
 BLYTHWOOD RD W/B E OF STRATHGOWAN CRES
(1 row)
```

Yes (in both dev and prod).  Now, what about conflation?

```sql
flashcrow=> select * from counts.arteries_centreline where arterycode = 29044;
 arterycode | centreline_type | centreline_id | direction | geom
------------+-----------------+---------------+-----------+------
      29044 |                 |               |           |
(1 row)
```

Ah!  This appears to be a conflation issue.  Looking deeper, we see that only one of the link IDs matches our `centreline.intersections` table:

```sql
flashcrow=> select "LINKID" from "TRAFFIC"."ARTERYDATA" where "ARTERYCODE" = 29044;
      LINKID
-------------------
 13455012@13455068
(1 row)

flashcrow=> select * from centreline.intersections where "centrelineId" = 13455068;
 centrelineId | centrelineType | classification | description | featureCode | geom | lat | lng
--------------+----------------+----------------+-------------+-------------+------+-----+-----
(0 rows)
```

**Comment by candu** [comment]
Looking at this from another direction: I see that there aren't that many counts available after mid-March in MOVE.  (To see this: go to MOVE dev, apply a date filter using the new Global Filters feature, pan around.)

This suggests there's a larger problem at work here.  Let's see if we can quantify the issue: for counts conducted on or after the 15th of March, how many of them belong to arterycodes that failed conflation?

```sql
WITH recent_arterycodes AS (
  SELECT DISTINCT("ARTERYCODE") AS arterycode FROM (
    SELECT DISTINCT("ARTERYCODE") FROM "TRAFFIC"."COUNTINFO" WHERE "COUNT_DATE" >= '2021-03-15'
    UNION ALL
    SELECT DISTINCT("ARTERYCODE") FROM "TRAFFIC"."COUNTINFOMICS" WHERE "COUNT_DATE" >= '2021-03-15'
  ) a
)
SELECT
  COUNT(*) AS total,
  COUNT(*) FILTER (WHERE "centreline_id" IS NULL) AS missing
FROM counts.arteries_centreline
JOIN recent_arterycodes USING (arterycode);

 total | missing
-------+---------
   150 |      52
```

So roughly one-third of these are failing conflation!  How does this compare to overall conflation rates?

```sql
SELECT
  COUNT(*) AS total,
  COUNT(*) FILTER (WHERE "centreline_id" IS NULL) AS missing
FROM counts.arteries_centreline;

 total | missing
-------+---------
 28967 |    1937
```

It's...a _lot_ worse.

**Comment by candu** [comment]
Made some updates to the way we handle conflation of "double-link" arterycodes (i.e. arterycodes whose `link_id` is of form `N1@N2`).

PR coming shortly.

**Comment by mkewins** [comment]
Great write-up @candu!
