### ISSUE TITLE
Age missing from the CSV download for Collision Directory Report

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#915]
**What Happened**
For a multi-location selection, the age column is blank for all values in the Collision Directory Report CSV download.

**What Should Happen**
Age should be present.

**To Reproduce**
- v1.3.1 on dev
- Firefox browser
- Locations (1) Lawrence / Howden / Underwriters (2) Birchmount / Canadian; without selecting intersections / midblocks in between

Steps to reproduce the bug:
1. Create a multi-location selection with two or more locations.
2. Go to View Data
3. Click on "View Reports" under the Collisions section
4. Download a CSV of the Directory Report
5. See that the age column is blank

**Screenshots**
n/a

**Additional Notes**
Do NOT attach reports here.

**Comment by candu** [comment]
Confirmed; the culprit appears to be this line in `ReportCollisionDirectory#getCsvDriverCells`:

```js
invage: this.getCollisionFactorCode('invage', invage),
```

...but there is no `collision_factors.invage` table, because it's not a coded field!  So this always returns `invage: null`, which shows up as a blank cell in the CSV.
