### ISSUE TITLE
500 error when trying to bulk export reports

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#916]
**What Happened**
Export reports returns a 500 server error.

**What Should Happen**
You should be able to download reports in bulk through the export report functionality.

**To Reproduce**
Steps to reproduce the bug:
1. Go to a multi-location selection (example: [Lawrence / Howden / Underwriters and Ellesmere / Birchmount](https://move.intra.dev-toronto.ca/view/location/s1:A0qnmBOgmmB/POINTS))
2. Scroll down to the Studies section
3. Click on Export Reports
4. Download as either CSV or PDF
5. Receive a 500 error page: "An internal server error occurred"

**Screenshots**
For frontend bugs, provide a browser screenshot if possible.  For backend bugs, screenshots of either the frontend dev tools (e.g. Network tab showing API responses or errors, Console tab showing errors) or the backend `node --inspect` dev tools (e.g. Debugger tab showing the issue) are helpful.

**Additional Notes**
This also failed for Collision reports at the same selected location.

Trying another location to confirm whether this is an isolated problem or a reporter problem...
- [York Mills / Don Mills to York Mills / Leslie](https://move.intra.dev-toronto.ca/view/location/s1:AwEnmB8SnmB/CORRIDOR); filtered to TMCs since May 10, 2016; that failed too

**Comment by mkewins** [comment]
I just noticed that the browser is redirecting to our ADFS authentication. So this might be the issue.

**Comment by candu** [comment]
Looking at this deeper: at [Ellesmere and Birchmount](https://move.intra.dev-toronto.ca/view/location/s1:A0qnmBOgmmB/POINTS/reports/TMC), the TMC summary report fails to load.

This is possibly related to #908 - investigating further.  (Not sure if this is the original issue @mkewins faced, since that _might_ be related to some kind of temporary ADFS outage as noted above.)

**Comment by candu** [comment]
Tried the latter "trivial time range" fix, but that looks strange in practice since TMC time buckets aren't all contiguous.  Going to go with the former "null-safe" fix.
