### ISSUE TITLE
TMC Summary Report fails to load at Spadina / Nassau

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#924]
**What Happened**
TMC Summary Report fails to load at Spadina / Nassau (px: 278).

**What Should Happen**
TMC Summary Report should load.

**To Reproduce**
Steps to reproduce the bug:
1. Search for `px: 278`
2. Click on View Data
3. Under Studies > Turning Movement Counts > click on View Reports
4. See that TMC Summary Report fails to load for the two most recent counts (2012-08-22 and 2007-07-18)

**Screenshots**
n/a

**Additional Notes**
`{statusCode: 500, error: "Internal Server Error", message: "An internal server error occurred"}`

**Comment by candu** [comment]
This should be fixed by #921 :

- these reports now load successfully in MOVE dev 1.3.2;
- looking at the reports, they appear to meet the conditions that triggered the bug mentioned in #916 , #908 and fixed in #921.

Marking closed for now.
