### ISSUE TITLE
Watch / unwatch requests and projects

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#942]
**Description**
Requesters can change the set of people who are notified of a request or project, but other people cannot add / remove themselves here.  This task changes that.

**Acceptance Criteria**
- [ ] for requests and projects, and for all users with `STUDY_REQUESTS` scope other than the requester:
  - [ ] if their user email address is _not_ present in `ccEmails`, they can "watch" the request to add themselves to `ccEmails`;
  - [ ] otherwise, they can "unwatch" the request to remove themselves from `ccEmails`.

**Additional Notes**
This adds a request management action that does _not_ need to be performed by either the requester or a user with `STUDY_REQUESTS_ADMIN` scope - so we might want to either a) add a new set of REST API endpoints for this, or b) change `StudyRequestPermissions` to allow this.

**Comment by mkewins** [comment]
This feature request may be revisited in future, but is not a part of near-term priorities.
