### ISSUE TITLE
Change requester of a request

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#943]
**Description**
Many staff are still used to a workflow where they send in forms / details of a count to be conducted (e.g. by email), and Data Collection enters those details into the relevant system (previously ATS, now MOVE).  This means Data Collection is still entering requests into MOVE on users' behalf - but for accuracy of request history, it's useful to link those requests to the original requester.

As an interim solution (until workflows are changed), this task adds the ability for Data Collection to change the requester of a request (i.e. from the Data Collection user to the original requester).

**Acceptance Criteria**
- [ ] `UserController` adds an autocomplete suggestion endpoint that:
  - [ ] matches users on _either_ their username or their email address;
  - [ ] is available to all authenticated users;
- [ ] this autocomplete suggestion endpoint is wrapped into a new `FcInputUserSearch` component in the UI;
- [ ] in View Request, users with `STUDY_REQUESTS_ADMIN` scope can change the requester of a request;
- [ ] users with `STUDY_REQUESTS` scope but without `STUDY_REQUESTS_ADMIN` scope cannot see the relevant controls.

**Comment by mkewins** [comment]
This feature request may be revisited in future, but is not a part of near-term priorities.
