### ISSUE TITLE
Don't display search bar when editing a bulk request

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#948]
**What Happened**
Do not display the search bar on the bulk request edit page.

**What Should Happen**
When editing a bulk request, you should only be able to edit the bulk request details (name, emails, notes), not the location of studies.

**To Reproduce**
Steps to reproduce the bug:
1. Go to Track Requests
2. Open any bulk / project request
3. Click "Edit"
4. See that on the map inset, there is a search bar ("Choose location or click on the map"); searching for a location does nothing

**Screenshots**
![Screenshot 2021-06-01 134944](https://user-images.githubusercontent.com/3179624/120368618-46ba2800-c2e0-11eb-8fdf-936410de8f20.png)

**Additional Notes**
n/a

**Comment by shinechaudhuri** [comment]
The Legend in this view should not be present either, the user should only be able to see the map

**Comment by mkewins** [comment]
Note on @shinechaudhuri's comment: the legend is also currently overlapping with the search bar, so removing the legend will solve this issue as well.
