### ISSUE TITLE
"Requested by me" filter not applied after login

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#949]
**What Happened**
When you first log in and load the Track Requests page, the filter "Requested by me" is displayed but is not applied to the list of requests.

**What Should Happen**
Only requests displayed by me should be rendered if the filter "Requested by me" is automatically selected.

**To Reproduce**
Steps to reproduce the bug:
1. From the sidebar, click on the "Track Requests" icon
2. Enter credentials and log in
3. MOVE redirects you to the Track Requests page
4. See error (screenshot below)

**Screenshots**
![Screenshot 2021-06-01 140001](https://user-images.githubusercontent.com/3179624/120369928-f93eba80-c2e1-11eb-88e6-4f5a8c0fa09e.png)

**Additional Notes**
I haven't submitted any studies from my account (Maddy!)
Tested in prod (v1.4.0)
Tested on Chrome

**Comment by mkewins** [comment]
Also seeing this in `dev`.

**Comment by candu** [comment]
This is a _race condition_ (-ish) bug.  Here's what happens, in order, for a non-Data Collection user:

1. the user loads Track Requests, which by default does not set the `userOnly` flag.
2. the `created()` hook in `FcMixinRouteAsync` fetches requests without `userOnly`.
3. the `created()` hook in `<FcRequestsTrack>` sets `userOnly = true`.
4. this triggers another fetch for requests, this time with `userOnly`.
5. the request with `userOnly` often fetches a much smaller result set...so it finishes first, and updates the table!
6. ...and then the request without `userOnly` finishes, and updates the table!

This is why, if you look closely, you'll see the correct set of requests flash before being replaced by the entire request list.  (As further evidence: if you clear the "Requested by me" filter, then re-apply it, it now works properly.)

Currently working on a fix here.
