### ISSUE TITLE
Track Requests UI changes

### ISSUE THREAD

**Issue by shinechaudhuri** [CityofToronto/bdit_flashcrow#951]
**What Happened**
Not enough padding in dropdown options for "Add To Project" button

**What Should Happen**
Add more padding for Create Project button dropdown, should be similar to Download button dropdown

------------------------ 

**What Happened**
Project icons in Track Request table are shown as map pins, "Add To Project" button is shown as a folder

**What Should Happen**
 Change Project icons to folder icons in table

------------------------ 

**What Happened**
View Request Info page's map shows studies when zoomed in, map becomes cluttered 

**What Should Happen**
Remove Studies icons in map, user is primarily looking for the locations of the requests in this page

------------------------ 

**What Happened**
Within a Project page, if there are numerous requests the table can be large and difficult for the user to action multiple items because they have to scroll up to see the action items

**What Should Happen**
Table options inside Project should be sticky when user is scrolling down list of requests

------------------------ 

**What Happened**
When removing a request from a Project, the snackbar/toast shows a general message

**What Should Happen**
Snackbar/toast should show the name of study that was removed, if multiple then use a number, eg. "4 studies were removed from the Project"

------------------------ 

**What Happened**
In the New Request flow, creating a new project presents a "Remove From Project" button. 

**What Should Happen**
Rename the button to "Remove" and put it next to the "Add To Project" button.

**Comment by candu** [comment]
Going to punt on this piece here:

> Table options inside Project should be sticky when user is scrolling down list of requests

This is a _bit_ more extensive than the other changes: we'd need to determine what the max height of the table should be (probably the height of the page, minus the topbar and nav header?), then give this area its own scrolling within the scrolling page.

Alternatively, we'd have to rework the whole page into a full-page layout that doesn't scroll, to give this table more space (that it can then use here.)
