### ISSUE TITLE
Classification ATR count shows up as "Unknown" type

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#952]
**What Happened**
A duplicate ATR count is showing up as "Unknown", with no reports associated.

**What Should Happen**
There are no "Unknown" count types.

**To Reproduce**
Steps to reproduce the bug:
1. Open the View Data page for [Bentworth Ave: Dufferin St – Groton St](https://move.intra.prod-toronto.ca/view/location/s1:ALLZDA/POINTS)
2. See error

**Screenshots**
<img width="473" alt="Unknown count type" src="https://user-images.githubusercontent.com/3179624/120559576-43ea3080-c3cf-11eb-9039-688e5f61eb62.png">

**Additional Notes**
Donna also reported "There are duplicate ATRs showing up at some locations." I've asked her for more examples, and to clarify whether the duplicate ATRs refer to the "Unknown" counts only, or actually duplicated ATRs.

**Comment by candu** [comment]
Here's a screenshot of the `/studies/byCentreline/summary` REST API response:

**Comment by mkewins** [comment]
Ahh, is that a classification count (ATR with classification data)? This has been highly requested, and there are open questions about how we handle it. Does it get its own study type? Is it a subtype of Speed / Volume ATRs? (functionally, it's collected same as any other ATR, but users specifically look for it)

**Comment by candu** [comment]
Fixed in QA: https://move.intra.qa-toronto.ca/view/location/s1:ALLZDA/POINTS - marking closed.
