### ISSUE TITLE
New Request freezes when creating a new project

### ISSUE THREAD

**Issue by shinechaudhuri** [CityofToronto/bdit_flashcrow#954]
**What Happened**
During usability tests, users wanted to add studies from other locations when requesting new studies, in Single Location mode. After clicking on Create New Project button, users were unable to Submit the study and the button froze. There was no way out for the user except to restart the request flow again.

**What Should Happen**
When clicking on the Submit button, the request should go through along with the Project creation. If it takes a while for it to load, users should be notified with an option to reload their request or to wait.

**To Reproduce**
Steps to reproduce the bug:
1. Go to Eglinton and Bayview
2. Click on 'New Request'
3. Click on Add Study on Bayview and Roehampton
4. Click on Add New Project
5. Enter Project Name
6. Click Submit

**Screenshots**
![image](https://user-images.githubusercontent.com/13545571/121205718-e5e1a100-c845-11eb-9d93-14cd3d06e815.png)

**Additional Notes**
Happened to other locations as well.

**Comment by candu** [comment]
Tracked down the cause: in `makeStudyRequestBulk()`, we set `notes: null` by default, but we don't allow `null` values for `notes` when validating a bulk request in the backend.

Fix coming shortly.
