### ISSUE TITLE
Last pre-release fixes for Version 1.5

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#962]
**Description**
This task collects small issues that came up during QA testing.

See [MOVE QA Testing v1.5 (internal-only)](https://docs.google.com/spreadsheets/d/1tTKRCAhTN14jzfjJvvzhuk0onBdLH0TP5CInaYaCXO4/edit?usp=sharing) for details.

**Acceptance Criteria**
- [x] show study purple squares on New Request and Edit Request

**Comment by shinechaudhuri** [comment]
Changes
- [ ]  Remove checkbox and have them selected as default for New Requests in Single Location mode
- [ ]  Create Project divider should have a similar padding as above 'Request Priority and Details' header

Bug:
- Users should not be able to Submit a Request if no study locations are selected via checkbox, Submit button should be in inactive state
- If user selects all Locations and then uses dropdown to select Midblocks and applies a Study Type, then User is shown a warning dialog saying the Intersections could not be changed, even if the user specifically selected Midblocks in the dropdown

**P1 Bug:**
- In ML mode, when making New Request and creating New Project, all locations are included in the New Project, even if user deselected some, or sometimes the request doesn't go through and the Submit button freezes

**Comment by candu** [comment]
@shinechaudhuri @mkewins there's a couple of areas of confusion here that we should probably discuss, as they might point to a) holdovers from the mental model of the previous design and/or b) lingering usability problems.

I'll attempt to describe how these things _currently_ work, why that is, and how it might be improved (taking into account feedback to that effect so far).  We can also discuss quickly in Design Critique today if that's helpful.

---

First: selection is no longer about which studies are or are not included in the request, but is instead about _editing_.  Selected studies can be edited using the top bar (to set study type, hours, duration) or using the map (to set location).  All studies listed are included in the request, regardless of whether they are selected.

The idea was to let the user build up a list ("shopping cart") of studies, and to reframe selection as a way to edit multiple things in that list at once.  I've seen similar patterns in shopping cart-like flows before, and IIRC in such flows selection usually means "I want to modify these things in some way", not "I want to order only these things".

One possibility would be to add the number of studies to the "Submit" button, or add copy elsewhere that makes it clear that all studies listed are being requested.

---

Second: the "Locations / Midblocks / Intersections" dropdown changes what the "Select All" checkbox operates on.  If the dropdown is in "Locations" mode when the user clicks the checkbox, it will select all locations.  If the user then switches to "Midblocks", it keeps the same selection, but now the "Select All" checkbox would toggle midblocks.

The idea here was to merge the intersections / midblocks steps into a single page: after all, these steps were doing very similar things, but keeping them separated made implementing a sensible add / remove study flow much more difficult.  (For instance: you're on the midblocks step.  So do we show only midblocks on the map?  And then what about the location search bar, which searches by intersection?)

One possibility to reduce confusion is something like the following:

- user is in "Locations" mode and selects all;
- user switches to "Midblocks" mode, at which point:
  - all non-midblock locations are deselected;
  - selection on non-midblock locations is disabled.

---

Third: there is no longer a sense of single-location vs. multi-location mode.  There is just New Request, which can create one or more study requests, and which can optionally lump those study requests into a project (either new or existing).  Both single-location selections and multi-location selections enter the same New Request flow; the initial state of that flow is just different in each case.

This reduces the maintenance burden of this part of MOVE considerably: we no longer have two completely separate flows, one of which is a 4-step wizard.  It also means that, if a user does enter New Request from a single-location selection, they can still add more studies - they could add a Ped Delay as well as a TMC at an intersection, for instance, or add ATRs on the adjacent midblocks.  This has the awesome side effect of bringing New Request much more in line with a "separate but related product" vision.

One possibility, as suggested, is to hide the checkboxes and topbar if only one study is being requested.  If we do that, IMHO it should remain obvious that the user can request more studies (e.g. by still showing the "use the map to add a study" message at top).

**Comment by mkewins** [comment]
some jot notes:
- i understood the selection checkboxes meant for editing via the top-bar, but @shinechaudhuri's confusion highlights that other users may be confused as well (especially since they're familiar with the existing study request flow, so the mental model hold-over may be relevant to others). regardless, there's apparent confusion over what selected / deselected means here.
- i think the "everything is included by default" method works for a limited number of selected locations, but would be cumbersome for ~10s (say, 50) locations. say you only want to create count requests for 20, then you have to go through and manually remove 30 locations. one question which could help clarify: do users come into the flow with the expectation of including most things, or only a few?
- the bullet points under "Second" took me a couple readthroughs to understand; i get it now, but unsure about how that interaction would feel

**Comment by mkewins** [comment]
notes from discussion:
- show the number of items in the selected state
- show the number of requests being submitted
- add edit location functionality to the card itself
  - notes on this: (1) we don't have a search index for midblocks; (2) there are some intersections in the city where two streets cross more than once. we'll need to have a map interaction for editing midblocks within the New Request flow.
  - add an "edit location" button on each card that works within the existing functionality and deselects anything else selected
- grey vs. blue icons: everything is blue by default; anything selected for editing is blue-on-white

**Comment by candu** [comment]
Closing out after recent QA testing - thanks everyone!
