### ISSUE TITLE
Upgrade Vue, Vuetify

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#968]
**Description**
MOVE uses Vue v2, but Vue is now on v3.  Vuetify (which we use for Material Design components) has a [Q3 2021 release target](https://vuetifyjs.com/en/introduction/roadmap/) for v3, which will itself use Vue v3.

This task 

**Acceptance Criteria**
- [x] investigate feasibility of upgrading to Vue 3.x ahead of Vuetify 3.x release;
- [ ] expand set of tasks here based on investigation.

**Comment by candu** [comment]
Vuetify 3.x is [currently in alpha](https://next.vuetifyjs.com/en/getting-started/installation/#how-to-report-an-issue-or-bug) - we should probably wait for something a _bit_ more stable before starting the Vuetify upgrade process.

**Comment by leonL** [comment]
I'm tracking and scheduling dependency updates as part of the release process. Closing this ticket
