### ISSUE TITLE
Post-Ped Delay cleanup

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#972]
**Description**
In #970 , we did a _lot_ of work to implement Ped Delay Summary reports in MOVE.  This task captures known cleanup work from that effort.

**Acceptance Criteria**
- [x] remove `lib/model/Category` and `lib/db/CategoryDAO` from codebase;
- [x] inline `"TRAFFIC"."ARTERYDATA"` queries in `lib/db/CountLocationDAO`, so that we can remove `lib/db/ArteryDAO`;
- [ ] create Ped Delay test dataset for use in Ped Delay-related tests;
- [x] remove unused method `CountLocationDAO.getApproachDirection`;
- [ ] transcribe statistics from a legacy report;
- [ ] add testing for `ReportPedDelaySummary`.

**Comment by leonL** [comment]
Migrated to Jira [MOVE-212]
