### ISSUE TITLE
Show one decimal place on summary stats for speed percentile reports

### ISSUE THREAD

**Issue by shinechaudhuri** [CityofToronto/bdit_flashcrow#974]
**What Happened**
An ATP user mentioned that the 46th percentile which is the median is the same value as the mean. He said he needs to know the mean, whether it's trending higher or lower and is expecting a decimal point. Are these rounded? Wanted to investigate this

**Comment by candu** [comment]
@shinechaudhuri I'm still not sure I understand here - the median is the 50th percentile, by definition; we provide 15th, 50th, 85th, and 95th percentile speeds as well as the mean.

Is it a traffic engineering convention / heuristic to use the 46th percentile as the mean?  In general, these would not necessarily be the same.  (A quick example: consider a list of 50 0s and 50 100s; the 46th percentile is 0, but the mean is 50.)

**Comment by candu** [comment]
Updated the issue title to focus on the decimal place part.

If we hear more about what the user meant by 46th percentile measurements, we can add an issue for that part - but in general 46th percentile and mean are different, as noted, so without more info there I'm reluctant to implement that part.
