### ISSUE TITLE
Need to investigate: inconsistency between Oracle / MOVE database in TRAFFIC.ACC

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#975]
**What Happened**
`.dat` files in the `/data/replicator` folder on MOVE AWS are old (CRASH from Apr 14, FLOW from Apr 10).  Also, @cczhu noted that the number of `TRAFFIC.ACC` records marked as being from 2020 is quite different in Oracle vs. MOVE: ~38k vs. ~49k.

However, replication appears (at least from notification emails and Airflow logs) to be continuing successfully.

**What Should Happen**
If replication succeeds, it should update to the newest available version of CRASH / FLOW data.

If replication cannot do that, it should fail, and should notify `move-ops` of this failure.

**Additional Notes**
Thoughts on testing consistency:

- check file timestamps;
- check `max("SENT_DATE")`;
- check `COUNT(*)` in Oracle vs. MOVE for only the last year's worth of data;

**Comment by mkewins** [comment]
Per @aharpalaniTO's investigation, the latest counts available in MOVE were loaded into FLOW on April 8th. This issue may extend beyond just collisions (as originally reported by Charles).

**Comment by candu** [comment]
From discussion on Slack:

> looked into this a bit further, and confirmed the COUNT-ACCDATE mismatch, but don't have any better ideas yet on why this might be happening.  it looks like:
> - the part of this job that runs on the replicator station is running successfully, and is generating a new version of ACC.dat every day;
> - the files are being copied to AWS, but the ACC.dat timestamp is indeed from Apr 14 (including on AWS qa, which shouldn't be affected by dev outages);
> - the Airflow jobs are all being marked successful;
> - the relevant tables do contain collisions from after Apr 14, but not in the correct numbers.

Based on this, there's a couple of follow-up questions for investigation:

- is data being copied from Oracle successfully?
- is data _actually_ being uploaded from `replicator` to AWS correctly?

**Comment by candu** [comment]
Technical investigation [here on Notion (internal-only)](https://www.notion.so/bditto/Replicator-Outage-Apr-Jun-2021-35eb3186c59a48e5b054255f9d8169ab).

**Comment by candu** [comment]
Update here: I've tracked this down to...an SSH key rotation issue.

We've been having an issue on AWS ETL dev (`flashcrow-etl.intra.dev-toronto.ca`) where, when too many things run at once, the box fails an AWS load-balancer health check...and is then replaced by a new box.  This was first noticed on April 27, ~2 weeks after the timestamp of `ACC.dat` on AWS ETL.

This resulted in the SSH key for AWS ETL dev no longer matching the `known_hosts` entry for that environment on `replicator`, which in turn caused `ssh`, `scp` to AWS ETL dev to fail.

When `replicator` copies data to our environments, it starts with dev, then QA, then prod...so it would try dev first, fail, and exit the replicator script without copying.

I've removed the offending `known_hosts` entry and regenerated by manually `ssh`'ing to AWS ETL dev.  I'll check next week to see if this has fixed the immediate issue.

However, this doesn't yet give us a good way to detect this in the future; I'll be investigating _that_ when I return next week.

**Comment by candu** [comment]
From @cczhu 's post-fix investigation, CRASH data appears to be replicating successfully again.

For FLOW data, we can do a similar investigation.  Let's do a similar month-by-month comparison on `COUNTINFO` for 2020-2021:

```sql
SELECT EXTRACT(MONTH FROM "COUNT_DATE") AS month,
       COUNT(*) AS n
FROM TRAFFIC.COUNTINFO
WHERE "COUNT_DATE" BETWEEN TO_DATE('2020-01-01', 'YYYY-MM-DD') AND TO_DATE('2021-12-31', 'YYYY-MM-DD')
GROUP BY EXTRACT(MONTH FROM "COUNT_DATE")
ORDER BY 1

     MONTH          N
---------- ----------
         1       2469
         2       2478
         3       3028
         4       2035
         5       2462
         6       2290
         7       1566
         8       1084
         9       1016
        10        845
        11        572
        12        682
```

```sql
SELECT EXTRACT(MONTH from "COUNT_DATE") AS month,
       COUNT(*) AS n
FROM "TRAFFIC"."COUNTINFO" WHERE "COUNT_DATE" BETWEEN '2020-01-01' AND '2021-12-31'
GROUP BY month
ORDER BY 1;

 month |  n
-------+------
     1 | 2469
     2 | 2478
     3 | 3028
     4 | 2035
     5 | 2462
     6 | 2290
     7 | 1396
     8 | 1084
     9 | 1016
    10 |  845
    11 |  572
    12 |  682
```

There _is_ a discrepancy here for `month = 7` (July), but it's also possible that those are counts that were loaded on Mon Jul 5.  A similar investigation on `COUNTINFOMICS` gives matching counts.

The files on AWS ETL dev also appear to be up-to-date.  So far, this looks reasonable; now we can focus attention on how to detect this in the future.

**Comment by candu** [comment]
So: detecting future issues.  One thing I note is that `replicator-local.ps1` uses `$ErrorActionPreference = "Stop"`, which functions similarly to [`set -e` in bash](https://stackoverflow.com/questions/19622198/what-does-set-e-mean-in-a-bash-script), and is therefore _usually_ a good idea.

However: we _also_ try to run `Exit-Error` inside an `if (-Not $?)` check in several places, as a quick way to send out error notifications.  These `Exit-Error` calls _will never run_: if the previous command failed, `$ErrorActionPreference = "Stop"` stops the script before we can check `$?`!

This gives us a few main options:

1. wrap `replicator-local.ps1` in a _second_ script that uses `$?` to check if it succeeded, and send a notification email from there;
2. use [`trap`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_trap?view=powershell-7.1) to handle all errors, instead of `if (-Not $?) { Exit-Error -message $msg }`;
3. use `$ErrorActionPreference = "Continue"` instead, and add a bunch more `Exit-Error` guards.

2) is easier to implement than 3), and has the benefit that we catch _all_ errors, with the tradeoff that we can no longer send a more specific error message.

Before deciding on an approach, however, I'm going to try making a few test PowerShell scripts to see how `trap`, `$ErrorActionPreference`, and `$?` interact.

**Comment by candu** [comment]
Ran a quick test with this script:

```powershell
$ErrorActionPreference = "Stop"

trap {
  echo "trapped!"
}

echo "This command will always succeed."

ls invalid-directory
if (-Not $?) {
  echo "could not ls invalid-directory"
}

ls .
if (-Not $?) {
  echo "could not ls ."
}
```

The `trap` is called by the `ls invalid-directory` failure, and the script exits because of `$ErrorActionPreference`; the `if (-Not $?)` checks are never run, as expected.

If we change this preference to `"Continue"`, `trap` is not called, the script runs to completion, and `if (-Not $?)` checks are run.

In both cases, the error message from the failing command is output to standard error.

So: we can _either_ use `$ErrorActionPreference = "Stop"` / `trap` _or_ use `if (-Not $?)`.  Even though we give up more precise error messages with the former route, thinking about it further it makes sense to keep `$ErrorActionPreference = "Stop"`, as it prevents entire classes of errors (e.g. if the dump fails, but then is `scp`'d anyways!)

Also, as mentioned, using `trap` here is much easier to do quickly.

**Comment by candu** [comment]
Added `trap` to replicator script.  As an additional safeguard, it probably makes sense to check `dat` file timestamps on the Airflow side.  Going to add that as well; PR coming shortly.

**Comment by candu** [comment]
Looks like this is working properly now - marking as closed.
