### ISSUE TITLE
Support multi-day / multi-direction studies in counts2 schema

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#976]
**Description**
In #971 , we introduced the `counts2` schema, which is used to store metadata and data for Ped Delay studies.  These studies contain a single count.

However, in legacy data models, some studies can have multiple counts.  An example is Volume ATRs, which can span multiple days, and which can also capture both directions of travel on two-way roads.  `counts.studies` handles this by grouping counts over runs of consecutive days, and at related arterycodes.

This task aims to implement similar groupings for `counts2`.

**Acceptance Criteria**
- [ ] introduce a count-grouping table between `counts2.studies` and `counts2.count_info` that identifies consecutive runs at the same `countLocationId`;
- [ ] use that table to group `counts2.count_info` entries and identify them using `countGroupId` values;
- [ ] use that table instead of `counts2.count_info` to define the `counts2.studies` view.

**Additional Notes**
For now, it's important that `counts2.studies` remains a view, and that queries against that view use relevant indexes (as identified via `EXPLAIN` / `EXPLAIN ANALYZE`).

The eventual goal is to use this new count-grouping table as `counts2.studies`, but for now we need to pull from both legacy and MOVE flows here.

**Comment by peter-lyons** [comment]
moved to jira
