### ISSUE TITLE
Use time ranges instead of timestamps in StudyDataDAO

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#977]
**Description**
`StudyDataDAO` currently returns objects `{ t, data }` for each database record in a count dataset.  For instance, a typical 8-hour TMC will be fetched as an array of 32 such objects, one per 15-minute bucket.  A 2-zone 8-hour Ped Delay might have 64 such objects, one per zone per 15-minute bucket.

This task aims to replace the `t` part of that object with a pair of timestamps `start` and `end`, describing the time range of the bucket.  This makes it clearer what the timestamp means - in legacy count data tables, TMCs use end-of-bucket as the timestamp, while ATRs use start-of-bucket!  It also prepares MOVE for other time bucket lengths (e.g. Origin-Destination uses 5-minute buckets; RESCU raw data uses 20-second buckets), and in general makes MOVE more future-proof (e.g. if there are ever variable-bucket-length counts, or if counts of the same type have different bucket lengths between them).

**Acceptance Criteria**
- [ ] `StudyDataDAO` returns objects `{ start, end, data }` for each database record;
- [ ] all report modules work with this new format;
- [ ] all other libraries that use count data work with this new format;
- [ ] all relevant tests have been updated accordingly, and pass.

**Comment by leonL** [comment]
Migrated to Jira [MOVE-210]
