### ISSUE TITLE
Improve analytics, logging across MOVE

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#978]
**Description**
In #861 , we noted specific needs around analytics for filters and reports.  Since that issue was filed, we've concluded that our current tool (Oracle Infinity) isn't well-suited to highly interactive single-page web applications - it assumes a more traditional content-heavy webpage.

In addition, while we have a decent amount of automated testing in place, and while users can report bugs to the MOVE team, we don't currently have any instrumentation around frontend errors, backend logs, slow database queries, etc.

This task aims to improve our practices here - it might need to be broken out into sub-tasks, and expanded as this is investigated further.

**Acceptance Criteria**
TBD: this likely requires some up-front investigation to select and assess possible tools here, as well as to define the scope of this work.

(In particular: we should be looking for the right tool, plus a quick-win smaller piece of the problem to apply it to.)

**Additional Notes**
There _are_ a lot of third-party tools (some open-source, some paid) out there that do some combination of analytics, log aggregation, and dashboards / monitoring / alerting.  We generally prefer to use open-source tools where at all possible, but this may be one area where it's worth breaking with that.

**Comment by mkewins** [comment]
We will pick up an investigation into better analytics tools in future.
