### ISSUE TITLE
Better geometry midpoint calculation in JavaScript 

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#979]
**Description**
`GeometryUtils.getGeometryMidpoint` uses a crude method to estimate the midpoints of GeoJSON geometries.  This task aims to implement this in a manner closer to the `ST_Closest(geom, ST_Centroid(geom))` method used in our ETL pipelines.

**Acceptance Criteria**
- [ ] midpoint calculation has been improved;
- [ ] `GeometryUtils` tests are updated;
- [ ] those tests include at least one side-by-side comparison with the results of `ST_Closest(geom, ST_Centroid(geom))`.

**Additional Notes**
turf.js is a promising library here; it provides [`nearestPointOnLine`](http://turfjs.org/docs/#nearestPointOnLine) and [`centroid`](http://turfjs.org/docs/#centroid).

**Comment by leonL** [comment]
moving to Jira
