### ISSUE TITLE
Replace use of Error with more specific Error subclasses

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#980]
**Description**
We use `throw new Error(msg)` in several places.  This task aims to replace those with more specific Error subclasses.

**Acceptance Criteria**
- [ ] all `throw new Error` instances have been replaced by more specific subclasses.

**Additional Notes**
One longer-term improvement here would be to make all MOVE application errors subclasses of a new `MoveError` class, which itself would extend `Error`.  We could then centralize serialization of MOVE application errors, which might also help with #978 (e.g. to facilitate better logging / tracking of frontend errors).

**Comment by leonL** [comment]
migrating to jira
