### ISSUE TITLE
Add confirmation modal before cancelling study requests

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#985]
**Description**
Before cancelling a request, users should be prompted to confirm or cancel the action.

**Acceptance Criteria**

- [ ] anytime a study request status is set to cancelled, add an confirmation modal before making the change
  - [ ] for all roles with permissions to update a study request to cancelled
  - [ ] on the request detail page > set status > click cancel
  - [ ] on the project details page > select one or more study requests from the table > set status > cancel
  - [ ] on the track requests page > select one or more study requests from the table > set status > cancel
- [ ] modal design pattern / copy below

**Additional Notes**
We have an existing pattern for this when cancelling out of the new study request flow.

In this case, let's go with the following copy (or similar):
Cancel request?
Are you sure you want to cancel the study request? This action can be reversed, but only by a member of the Data Collection team (put their email here).
No, don't cancel
Yes, cancel request

(This example is meant to illustrate the type of alert and copy; please use MOVE design system for font, sizes, design patterns, etc.)
![Screenshot 2021-06-24 182727](https://user-images.githubusercontent.com/3179624/123342530-c6649c80-d504-11eb-8473-d9e6199b97b3.png)

**Comment by candu** [comment]
@leonL - a good first issue for seeing how dialogs work in MOVE, and for touching on the permissions model in MOVE a bit.
