### ISSUE TITLE
Study icons with Ped Delays are duplicated and offset

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#993]
**What Happened**
Where there are Ped Delay studies, the map icons are duplicated. Two purple study icons are present on the map. The duplicates are offset to the West by about ~10m. Only the duplicated icons show up when studies are filtered by Ped Delays.

**What Should Happen**
Only one set of study icons should be present on the map for a single intersection. When filtered, the icons at the _true_ intersection / location should show up in filtered results.

**To Reproduce**
Steps to reproduce the bug:
1. Go to MOVE dev, 1.5.1. We tested on both Chrome _or_ Edge, and we are seeing this on both browsers.
2. Apply the "Ped Delay and Classification" study type filter.
3. Zoom into one study icon.
4. See first error: study icons are offset from the intersection by ~10 meters.
5. Remove the filter by clicking the "X" beside the filter.
6. See second error: there are two study icons per intersection.

**Screenshots**
![Screenshot 2021-06-28 131956](https://user-images.githubusercontent.com/3179624/123678480-5875e900-d814-11eb-9a4a-0dab96454970.png)

**Additional Notes**

**Comment by mkewins** [comment]
In the screenshot, both the circled study icons are tagged as "Dupont / Perth".

**Comment by candu** [comment]
Initial guess: this is a projection issue for ped delays that were geolocated using our ATS dump.  If that were true, I'd expect to be able to find a ped delay that wasn't geolocated using ATS, and that is correctly located on the map.

**Comment by candu** [comment]
A quick check turns up a couple such ped delays:

- [Ronald and Castlefield](https://move.intra.dev-toronto.ca/view/location/s1:AigrmB/POINTS);
- [Vaughan and Atlas](https://move.intra.dev-toronto.ca/view/location/s1:AqWsmB/POINTS).

We can use an analysis similar to [this one for nodes (internal-only)](https://www.notion.so/bditto/Arterycode-Conflation-bc87f8cace6645f3bade59b84e84661e#45861a220c3f4422be1ac002421533e0) to help figure out what the right correction approach is here.  There are a couple of things we can try:

- find a similar hardcoded translation to what we have for CRASH data;
- re-project (maybe this is _also_ SRID 4269?)
- some combination of the above.

**Comment by candu** [comment]
Testing distances from `counts2.count_locations` to associated `centreline.intersections`:

```sql
WITH coords AS (
	SELECT
    cl.id,
    ST_Transform(cl.geom, 2952) AS cl_geom,
    ST_Transform(i.geom, 2952) AS i_geom
	FROM counts2.count_locations cl
	JOIN centreline.intersections i USING ("centrelineType", "centrelineId")
), distances AS (
  SELECT ST_Distance(cl_geom, i_geom) AS dist FROM coords
)
select
  round(min(dist)::numeric, 3) as p0,
  round(percentile_cont(0.01) within group (order by dist)::numeric, 3) as p1,
  round(percentile_cont(0.1) within group (order by dist)::numeric, 3) as p10,
  round(percentile_cont(0.25) within group (order by dist)::numeric, 3) as p25,
  round(percentile_cont(0.5) within group (order by dist)::numeric, 3) as p50,
  round(percentile_cont(0.75) within group (order by dist)::numeric, 3) as p75,
  round(percentile_cont(0.9) within group (order by dist)::numeric, 3) as p90,
  round(percentile_cont(0.99) within group (order by dist)::numeric, 3) as p99,
  round(max(dist)::numeric, 3) as p100
from distances;
```

This gives the following distribution:

```
  p0   |  p1   |  p10   |  p25   |  p50   |  p75   |  p90   |  p99   |  p100  
-------+-------+--------+--------+--------+--------+--------+--------+--------
 0.000 | 0.000 | 16.692 | 16.946 | 17.100 | 17.290 | 17.517 | 17.836 | 19.960
```

(Presumably the `p0` / `p1` values are from those non-ATS-geocoded intersections.)

We can also look at the direction of error:

```sql
WITH coords AS (
	SELECT
    cl.id,
    ST_Transform(cl.geom, 2952) AS cl_geom,
    ST_Transform(i.geom, 2952) AS i_geom
	FROM counts2.count_locations cl
	JOIN centreline.intersections i USING ("centrelineType", "centrelineId")
), distances AS (
  SELECT degrees(ST_Azimuth(cl_geom, i_geom)) AS dist FROM coords
)
select
  round(min(dist)::numeric, 3) as p0,
  round(percentile_cont(0.01) within group (order by dist)::numeric, 3) as p1,
  round(percentile_cont(0.1) within group (order by dist)::numeric, 3) as p10,
  round(percentile_cont(0.25) within group (order by dist)::numeric, 3) as p25,
  round(percentile_cont(0.5) within group (order by dist)::numeric, 3) as p50,
  round(percentile_cont(0.75) within group (order by dist)::numeric, 3) as p75,
  round(percentile_cont(0.9) within group (order by dist)::numeric, 3) as p90,
  round(percentile_cont(0.99) within group (order by dist)::numeric, 3) as p99,
  round(max(dist)::numeric, 3) as p100
from distances;
```

```
   p0   |   p1   |  p10   |  p25   |  p50   |  p75   |  p90   |   p99   |  p100   
--------+--------+--------+--------+--------+--------+--------+---------+---------
 18.772 | 64.047 | 68.749 | 68.898 | 69.029 | 69.180 | 69.359 | 268.721 | 351.289
```

From here, we can try different fixes above.  First, treating count locations as SRID 4269, and reprojecting to SRID 4326:

```
-- distances

  p0   |  p1   |  p10   |  p25   |  p50   |  p75   |  p90   |  p99   |  p100  
-------+-------+--------+--------+--------+--------+--------+--------+--------
 0.000 | 4.781 | 16.754 | 16.963 | 17.107 | 17.293 | 17.519 | 17.837 | 19.960
```

Second, applying a similar correction factor to CRASH data:

```
  p0   |  p1   |  p10  |  p25  |  p50  |  p75  |  p90  |  p99   |  p100  
-------+-------+-------+-------+-------+-------+-------+--------+--------
 0.768 | 1.233 | 1.324 | 1.371 | 1.464 | 1.556 | 1.741 | 23.756 | 32.469
```

This one looks _much_ better.  Playing around with the correction factor a bit, we can get even closer using `(0.000200, 0.000055)`:

```
  p0   |  p1   |  p10  |  p25  |  p50  |  p75  |  p90  |  p99   |  p100  
-------+-------+-------+-------+-------+-------+-------+--------+--------
 0.006 | 0.029 | 0.077 | 0.133 | 0.237 | 0.391 | 0.633 | 23.342 | 32.409
```

(Again, now the high end of the distribution is probably non-ATS-geocoded counts.)

**Comment by candu** [comment]
Should be fixed in dev now - PR coming shortly.
