### ISSUE TITLE
Midblocks missing names

### ISSUE THREAD

**Issue by mkewins** [CityofToronto/bdit_flashcrow#998]
**What Happened**
Some midblocks are missing a name (...and it's rendering parts of the application unusable).

**What Should Happen**
Midblocks should have a name. If we aren't able to identify a name for the midblock, core user flows (View Data, New Study Request), should still be accessible to users.

**To Reproduce**
Steps to reproduce the bug:
1. Open MOVE
2. Locate an intersection
3. Hover over an adjacent midblock
4. See that the tooltip is blank
5. Click on "View Data"
6. See error: View Data page opens briefly, shuts immediately before rendering anything, and the map zooms out to the entire City of Toronto.

Examples:
- Avenue Road just south of [Avenue / Tranby](https://move.intra.prod-toronto.ca/view/location/s1:A7V48A/POINTS)
- The Esplanade just east of [The Esplanade / Princess](https://move.intra.prod-toronto.ca/view/location/s1:AilvmB/POINTS)

OR

1. Go to the Track Requests page
2. Locate request [#108](https://move.intra.prod-toronto.ca/requests/study/108) or [#446](https://move.intra.prod-toronto.ca/requests/study/446)
3. See that the request is for a latitude / longitude coordinate. When hovering over the location, the tooltip is blank.

**Screenshots**
![Screenshot 2021-06-29 204401](https://user-images.githubusercontent.com/3179624/123885539-a6294900-d91b-11eb-8fe8-2a636902b408.png)

**Additional Notes**
n/a

**Comment by candu** [comment]
Closing out, now that v1.6 has been released.  I've also filed #1062 to capture the broader problem with DAG scheduling.
