### ISSUE TITLE
Manual cleanup: for 3-zone Ped Delays, only store the combined Excel sheet

### ISSUE THREAD

**Issue by candu** [CityofToronto/bdit_flashcrow#999]
**Description**
As mentioned in comments to #996 :

> This comes from source file /data/ped_delays/OLD/PED_DELAYS/2020/excel/97674_GEARY AVE and OSSINGTON AVE_Zone C.json - the problem here is that, in the network drive, ped delays with more than 2 zones often show up as multiple files:
>
> 1. one file covering zones A, B;
> 2. one file covering zone C;
> 3. one file that combines A, B, C.

This task is a _manual cleanup_ task to ensure that the MOVE intake directory on the network drive only has 3) above, and does not have 1) or 2).

**Acceptance Criteria**
- [ ] for all years `yyyy`, `NEW/PED_DELAYS/yyyy`:
  - [ ] still contains all 1-zone or 2-zone ped delay counts;
  - [ ] contains only the combined files (i.e. 3) above) for ped delay counts with 3 or more zones.

We can prioritize ped delays from 2015 onwards, but should eventually extend this to all historical ped delays.

**Additional Notes**
An example of this is the ped delay count at Geary / Ossington from 2020, which has three files in `L:\TDCSB\PROJECT\DATA COLLECTION GROUP\3 - MANUAL COUNTS\2020 Manual Counts\PED DELAY`:

1. `97674_GEARY AVE and OSSINGTON AVE Zones A B.xlsx`;
2. `97674_GEARY AVE and OSSINGTON AVE_Zone C.xlsx`
3. `97674_GEARY AVE AND OSSINGTON AVE_PedDelay_R_3ZONES.xlsx`

As above, we'd only want 3) in the `NEW/PED_DELAYS/2020` folder, not 1) or 2) - that is, only the `PedDelay_R_3ZONES` file should be saved in that folder.

I'm unclear on whether it's useful to store 1), 2) _somewhere_ for archival purposes.  Until we have a 100% clear answer to that, we should set them aside in a separate network drive folder; the exact folder hierarchy there doesn't matter.

**Comment by peter-lyons** [comment]
moved to jira
